# -*- coding: utf-8 -*-
# Arquivo gerado automaticamente a partir do Jupyter

SETORIAL_B3 = {'AALR': {'nome': 'ALLIAR',
          'segmento': 'Hospitalares, Análises e Diagnósticos',
          'setor': 'Saúde',
          'subsetor': 'Serviços Médico'},
 'ABCB': {'nome': 'ABC BRASIL', 'segmento': 'Bancos', 'setor': 'Financeiro', 'subsetor': 'Intermediários Financeiros'},
 'ABEV': {'nome': 'AMBEV S/A',
          'segmento': 'Cervejas e Refrigerantes',
          'setor': 'Consumo não Cíclico',
          'subsetor': 'Bebidas'},
 'ADMF': {'nome': 'CIABRASF', 'segmento': 'Holdings', 'setor': 'Financeiro', 'subsetor': 'Holdings Diversificadas'},
 'AERI': {'nome': 'AERIS',
          'segmento': 'Máq. e Equip. Industriais',
          'setor': 'Bens Industriais',
          'subsetor': 'Máquinas e Equipamentos'},
 'AESO': {'nome': 'AESOPERACOES', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'AFLT': {'nome': 'AFLUENTE T', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'AGRO': {'nome': 'BRASILAGRO', 'segmento': 'Agricultura', 'setor': 'Consumo não Cíclico', 'subsetor': 'Agropecuária'},
 'AGRU': {'nome': 'GRUAIRPORT',
          'segmento': 'S. de Apoio e Armazenagem',
          'setor': 'Bens Industriais',
          'subsetor': 'Transporte'},
 'AGXY': {'nome': 'AGROGALAXY', 'segmento': 'Agricultura', 'setor': 'Consumo não Cíclico', 'subsetor': 'Agropecuária'},
 'AHEB': {'nome': 'SPTURIS', 'segmento': 'Eventos e Shows', 'setor': 'Consumo Cíclico', 'subsetor': 'Viagens e Lazer'},
 'ALLD': {'nome': 'ALLIED', 'segmento': 'Eletros.', 'setor': 'Consumo Cíclico', 'subsetor': 'Comércio Varejista'},
 'ALOS': {'nome': 'ALLOS', 'segmento': 'Exploração de Imóveis', 'setor': 'Financeiro', 'subsetor': 'Imóveis'},
 'ALPA': {'nome': 'ALPARGATAS',
          'segmento': 'Calçados',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Tecidos, Vestuário e Calçados'},
 'ALPK': {'nome': 'ESTAPAR', 'segmento': 'S. Diversos', 'setor': 'Bens Industriais', 'subsetor': 'Serviços Diversos'},
 'ALUP': {'nome': 'ALUPAR', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'AMAR': {'nome': 'LOJAS MARISA',
          'segmento': 'Vestuário e Calçados',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Comércio Varejista'},
 'AMBP': {'nome': 'AMBIPAR', 'segmento': 'Água', 'setor': 'Utilidade Pública', 'subsetor': 'Saneamento'},
 'AMER': {'nome': 'AMERICANAS',
          'segmento': 'Produtos Diversos',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Comércio Varejista'},
 'AMOB': {'nome': 'AUTOMOB',
          'segmento': 'Auto. e Moto.',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Automóveis e Motocicletas'},
 'ANIM': {'nome': 'ANIMA', 'segmento': 'Serviços Educacionais', 'setor': 'Consumo Cíclico', 'subsetor': 'Diversos'},
 'APTI': {'nome': 'ALIPERTI', 'segmento': 'Agricultura', 'setor': 'Consumo não Cíclico', 'subsetor': 'Agropecuária'},
 'ARML': {'nome': 'ARMAC',
          'segmento': 'Máq. e Equip. Industriais',
          'setor': 'Bens Industriais',
          'subsetor': 'Máquinas e Equipamentos'},
 'ASAI': {'nome': 'ASSAI',
          'segmento': 'Alimentos',
          'setor': 'Consumo não Cíclico',
          'subsetor': 'Comércio e Distribuição'},
 'ATED': {'nome': 'ATOM EDUC', 'segmento': 'Serviços Educacionais', 'setor': 'Consumo Cíclico', 'subsetor': 'Diversos'},
 'AURA': {'nome': 'AURA 360', 'segmento': 'Minerais Metál.', 'setor': 'Materiais Básicos', 'subsetor': 'Mineração'},
 'AURE': {'nome': 'AUREN', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'AVLL': {'nome': 'ALPHAVILLE',
          'segmento': 'Incorporações',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Construção Civil'},
 'AZEV': {'nome': 'AZEVEDO',
          'segmento': 'Construção Pesada',
          'setor': 'Bens Industriais',
          'subsetor': 'Construção e Engenharia'},
 'AZTE': {'nome': 'AZT ENERGIA',
          'segmento': 'Explo., Refino e Distr.',
          'setor': 'Energia',
          'subsetor': 'Petro., Gás e Bio.'},
 'AZUL': {'nome': 'AZUL',
          'segmento': 'L. Aéreas de Passageiros',
          'setor': 'Bens Industriais',
          'subsetor': 'Transporte'},
 'AZZA': {'nome': 'AZZAS 2154',
          'segmento': 'Vestuário e Calçados',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Comércio Varejista'},
 'B3SA': {'nome': 'B3', 'segmento': 'Diversos', 'setor': 'Financeiro', 'subsetor': 'Serviços Financeiros Diversos'},
 'BALM': {'nome': 'BAUMER', 'segmento': 'Equipamentos Médicos e Hosp.', 'setor': 'Saúde', 'subsetor': 'Equipamentos'},
 'BAUH': {'nome': 'EXCELSIOR',
          'segmento': 'Carnes e Derivados',
          'setor': 'Consumo não Cíclico',
          'subsetor': 'Alimentos Processados'},
 'BAZA': {'nome': 'AMAZONIA', 'segmento': 'Bancos', 'setor': 'Financeiro', 'subsetor': 'Intermediários Financeiros'},
 'BBAS': {'nome': 'BRASIL', 'segmento': 'Bancos', 'setor': 'Financeiro', 'subsetor': 'Intermediários Financeiros'},
 'BBDC': {'nome': 'BRADESCO', 'segmento': 'Bancos', 'setor': 'Financeiro', 'subsetor': 'Intermediários Financeiros'},
 'BBML': {'nome': 'BBMLOGISTICA',
          'segmento': 'S. Diversos',
          'setor': 'Bens Industriais',
          'subsetor': 'Serviços Diversos'},
 'BBSE': {'nome': 'BBSEGURIDADE',
          'segmento': 'Seguradoras',
          'setor': 'Financeiro',
          'subsetor': 'Previdência e Seguros'},
 'BDLL': {'nome': 'BARDELLA',
          'segmento': 'Máq. e Equip. Industriais',
          'setor': 'Bens Industriais',
          'subsetor': 'Máquinas e Equipamentos'},
 'BEEF': {'nome': 'MINERVA',
          'segmento': 'Carnes e Derivados',
          'setor': 'Consumo não Cíclico',
          'subsetor': 'Alimentos Processados'},
 'BEES': {'nome': 'BANESTES', 'segmento': 'Bancos', 'setor': 'Financeiro', 'subsetor': 'Intermediários Financeiros'},
 'BETP': {'nome': 'BETAPART', 'segmento': 'Segmento: Outros', 'setor': 'Setor: Outros', 'subsetor': 'Subsetor: Outros'},
 'BGIP': {'nome': 'BANESE', 'segmento': 'Bancos', 'setor': 'Financeiro', 'subsetor': 'Intermediários Financeiros'},
 'BHIA': {'nome': 'CASAS BAHIA', 'segmento': 'Eletros.', 'setor': 'Consumo Cíclico', 'subsetor': 'Comércio Varejista'},
 'BIED': {'nome': 'BIOMA EDUC',
          'segmento': 'Serviços Educacionais',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Diversos'},
 'BIOM': {'nome': 'BIOMM',
          'segmento': 'Medic. e Outros',
          'setor': 'Saúde',
          'subsetor': 'Medicamentos e Outros Produtos'},
 'BLAU': {'nome': 'BLAU', 'segmento': 'Medicamentos e Outros', 'setor': 'Saúde', 'subsetor': 'Comércio e Distribuição'},
 'BMEB': {'nome': 'MERCANTIL', 'segmento': 'Bancos', 'setor': 'Financeiro', 'subsetor': 'Intermediários Financeiros'},
 'BMGB': {'nome': 'BANCO BMG', 'segmento': 'Bancos', 'setor': 'Financeiro', 'subsetor': 'Intermediários Financeiros'},
 'BMIN': {'nome': 'MERC INVEST', 'segmento': 'Bancos', 'setor': 'Financeiro', 'subsetor': 'Intermediários Financeiros'},
 'BMKS': {'nome': 'BIC MONARK', 'segmento': 'Bicicletas', 'setor': 'Consumo Cíclico', 'subsetor': 'Viagens e Lazer'},
 'BMOB': {'nome': 'BEMOBI TECH',
          'segmento': 'Programas e S.',
          'setor': 'Tecnologia da Informação',
          'subsetor': 'Softwares e S.'},
 'BNBR': {'nome': 'NORD BRASIL', 'segmento': 'Bancos', 'setor': 'Financeiro', 'subsetor': 'Intermediários Financeiros'},
 'BOBR': {'nome': 'BOMBRIL',
          'segmento': 'Prod. de Limpeza',
          'setor': 'Consumo não Cíclico',
          'subsetor': 'Cuidado Pessoal e Limpeza'},
 'BPAC': {'nome': 'BTGP BANCO', 'segmento': 'Bancos', 'setor': 'Financeiro', 'subsetor': 'Intermediários Financeiros'},
 'BPAN': {'nome': 'BANCO PAN', 'segmento': 'Bancos', 'setor': 'Financeiro', 'subsetor': 'Intermediários Financeiros'},
 'BPAR': {'nome': 'BANPARA', 'segmento': 'Bancos', 'setor': 'Financeiro', 'subsetor': 'Intermediários Financeiros'},
 'BRAP': {'nome': 'BRADESPAR', 'segmento': 'Minerais Metál.', 'setor': 'Materiais Básicos', 'subsetor': 'Mineração'},
 'BRAV': {'nome': 'BRAVA', 'segmento': 'Explo., Refino e Distr.', 'setor': 'Energia', 'subsetor': 'Petro., Gás e Bio.'},
 'BRBI': {'nome': 'BR PARTNERS', 'segmento': 'Bancos', 'setor': 'Financeiro', 'subsetor': 'Intermediários Financeiros'},
 'BRFS': {'nome': 'BRF SA',
          'segmento': 'Carnes e Derivados',
          'setor': 'Consumo não Cíclico',
          'subsetor': 'Alimentos Processados'},
 'BRKM': {'nome': 'BRASKEM', 'segmento': 'Petroquímicos', 'setor': 'Materiais Básicos', 'subsetor': 'Químicos'},
 'BRQB': {'nome': 'BRQ',
          'segmento': 'Programas e S.',
          'setor': 'Tecnologia da Informação',
          'subsetor': 'Softwares e S.'},
 'BRSR': {'nome': 'BANRISUL', 'segmento': 'Bancos', 'setor': 'Financeiro', 'subsetor': 'Intermediários Financeiros'},
 'BRST': {'nome': 'BRISANET', 'segmento': 'Tele.', 'setor': 'Comunicações', 'subsetor': 'Telecomunicações'},
 'BSCS': {'nome': 'BRAZILIAN SC',
          'segmento': 'Securitizadoras',
          'setor': 'Financeiro',
          'subsetor': 'Securitizadoras de Recebíveis'},
 'BSLI': {'nome': 'BRB BANCO', 'segmento': 'Bancos', 'setor': 'Financeiro', 'subsetor': 'Intermediários Financeiros'},
 'CAFR': {'nome': 'CARREFOUR AS',
          'segmento': 'Alimentos',
          'setor': 'Consumo não Cíclico',
          'subsetor': 'Comércio e Distribuição'},
 'CALI': {'nome': 'CONST A LIND',
          'segmento': 'Incorporações',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Construção Civil'},
 'CAMB': {'nome': 'CAMBUCI',
          'segmento': 'Calçados',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Tecidos, Vestuário e Calçados'},
 'CAML': {'nome': 'CAMIL',
          'segmento': 'Alimentos Diversos',
          'setor': 'Consumo não Cíclico',
          'subsetor': 'Alimentos Processados'},
 'CASH': {'nome': 'MELIUZ',
          'segmento': 'Programas e S.',
          'setor': 'Tecnologia da Informação',
          'subsetor': 'Softwares e S.'},
 'CASN': {'nome': 'CASAN', 'segmento': 'Água', 'setor': 'Utilidade Pública', 'subsetor': 'Saneamento'},
 'CATA': {'nome': 'IND CATAGUAS',
          'segmento': 'Fios e Tecidos',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Tecidos, Vestuário e Calçados'},
 'CBAV': {'nome': 'CBA', 'segmento': 'Minerais Metál.', 'setor': 'Materiais Básicos', 'subsetor': 'Mineração'},
 'CBEE': {'nome': 'AMPLA ENERG', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'CCTY': {'nome': 'RDVC CITY', 'segmento': 'Incorporações', 'setor': 'Consumo Cíclico', 'subsetor': 'Construção Civil'},
 'CEAB': {'nome': 'CEA MODAS',
          'segmento': 'Vestuário e Calçados',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Comércio Varejista'},
 'CEBR': {'nome': 'CEB', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'CEDO': {'nome': 'CEDRO',
          'segmento': 'Fios e Tecidos',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Tecidos, Vestuário e Calçados'},
 'CEEB': {'nome': 'COELBA', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'CEED': {'nome': 'CEEE-D', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'CEGR': {'nome': 'CEG', 'segmento': 'Gás', 'setor': 'Utilidade Pública', 'subsetor': 'Utilidade publ. Gás'},
 'CGAS': {'nome': 'COMGAS', 'segmento': 'Gás', 'setor': 'Utilidade Pública', 'subsetor': 'Utilidade publ. Gás'},
 'CGRA': {'nome': 'GRAZZIOTIN',
          'segmento': 'Vestuário e Calçados',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Comércio Varejista'},
 'CLSC': {'nome': 'CELESC', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'CMIG': {'nome': 'CEMIG', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'CMIN': {'nome': 'CSNMINERACAO', 'segmento': 'Minerais Metál.', 'setor': 'Materiais Básicos', 'subsetor': 'Mineração'},
 'COCE': {'nome': 'COELCE', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'COGN': {'nome': 'COGNA ON', 'segmento': 'Serviços Educacionais', 'setor': 'Consumo Cíclico', 'subsetor': 'Diversos'},
 'COMR': {'nome': 'COMERC PAR', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'CPFE': {'nome': 'CPFL ENERGIA', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'CPLE': {'nome': 'COPEL', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'CRPG': {'nome': 'CRISTAL', 'segmento': 'Químicos Diversos', 'setor': 'Materiais Básicos', 'subsetor': 'Químicos'},
 'CRTE': {'nome': 'CONC RIO TER',
          'segmento': 'Exploração de Rodovias',
          'setor': 'Bens Industriais',
          'subsetor': 'Transporte'},
 'CSAN': {'nome': 'COSAN', 'segmento': 'Explo., Refino e Distr.', 'setor': 'Energia', 'subsetor': 'Petro., Gás e Bio.'},
 'CSED': {'nome': 'CRUZEIRO EDU',
          'segmento': 'Serviços Educacionais',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Diversos'},
 'CSMG': {'nome': 'COPASA', 'segmento': 'Água', 'setor': 'Utilidade Pública', 'subsetor': 'Saneamento'},
 'CSNA': {'nome': 'SID NACIONAL',
          'segmento': 'Siderurgia',
          'setor': 'Materiais Básicos',
          'subsetor': 'Siderurgia e Metalurgia'},
 'CSUD': {'nome': 'CSU DIGITAL',
          'segmento': 'Diversos',
          'setor': 'Financeiro',
          'subsetor': 'Serviços Financeiros Diversos'},
 'CTAX': {'nome': 'CONTAX', 'segmento': 'S. Diversos', 'setor': 'Bens Industriais', 'subsetor': 'Serviços Diversos'},
 'CTBA': {'nome': 'CEPAC - CTBA', 'segmento': 'Outros títulos', 'setor': 'Financeiro', 'subsetor': 'Títulos'},
 'CTCA': {'nome': 'CTC S.A.', 'segmento': 'Agricultura', 'setor': 'Consumo não Cíclico', 'subsetor': 'Agropecuária'},
 'CTKA': {'nome': 'KARSTEN',
          'segmento': 'Fios e Tecidos',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Tecidos, Vestuário e Calçados'},
 'CTNM': {'nome': 'COTEMINAS',
          'segmento': 'Fios e Tecidos',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Tecidos, Vestuário e Calçados'},
 'CTSA': {'nome': 'SANTANENSE',
          'segmento': 'Fios e Tecidos',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Tecidos, Vestuário e Calçados'},
 'CURY': {'nome': 'CURY S/A', 'segmento': 'Incorporações', 'setor': 'Consumo Cíclico', 'subsetor': 'Construção Civil'},
 'CVCB': {'nome': 'CVC BRASIL',
          'segmento': 'Viagens e Turismo',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Viagens e Lazer'},
 'CXSE': {'nome': 'CAIXA SEGURI',
          'segmento': 'Seguradoras',
          'setor': 'Financeiro',
          'subsetor': 'Previdência e Seguros'},
 'CYRE': {'nome': 'CYRELA REALT',
          'segmento': 'Incorporações',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Construção Civil'},
 'DASA': {'nome': 'DASA',
          'segmento': 'Hospitalares, Análises e Diagnósticos',
          'setor': 'Saúde',
          'subsetor': 'Serviços Médico'},
 'DESK': {'nome': 'DESKTOP', 'segmento': 'Tele.', 'setor': 'Comunicações', 'subsetor': 'Telecomunicações'},
 'DEXP': {'nome': 'DEXXOS PAR', 'segmento': 'Petroquímicos', 'setor': 'Materiais Básicos', 'subsetor': 'Químicos'},
 'DIRR': {'nome': 'DIRECIONAL',
          'segmento': 'Incorporações',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Construção Civil'},
 'DMVF': {'nome': 'D1000VFARMA',
          'segmento': 'Medicamentos e Outros',
          'setor': 'Saúde',
          'subsetor': 'Comércio e Distribuição'},
 'DOHL': {'nome': 'DOHLER',
          'segmento': 'Fios e Tecidos',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Tecidos, Vestuário e Calçados'},
 'DOTZ': {'nome': 'DOTZ SA',
          'segmento': 'Programas de Fidelização',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Diversos'},
 'DTCY': {'nome': 'DTCOM-DIRECT',
          'segmento': 'S. Diversos',
          'setor': 'Bens Industriais',
          'subsetor': 'Serviços Diversos'},
 'DXCO': {'nome': 'DEXCO', 'segmento': 'Madeira', 'setor': 'Materiais Básicos', 'subsetor': 'Madeira e Papel'},
 'EALT': {'nome': 'ACO ALTONA',
          'segmento': 'Máq. e Equip. Industriais',
          'setor': 'Bens Industriais',
          'subsetor': 'Máquinas e Equipamentos'},
 'ECOR': {'nome': 'ECORODOVIAS',
          'segmento': 'Exploração de Rodovias',
          'setor': 'Bens Industriais',
          'subsetor': 'Transporte'},
 'EFXB': {'nome': 'EQUIFAXBRL',
          'segmento': 'Diversos',
          'setor': 'Financeiro',
          'subsetor': 'Serviços Financeiros Diversos'},
 'EGGY': {'nome': 'GRANJA FARIA',
          'segmento': 'Agricultura',
          'setor': 'Consumo não Cíclico',
          'subsetor': 'Agropecuária'},
 'EGIE': {'nome': 'ENGIE BRASIL', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'EKTR': {'nome': 'ELEKTRO', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'ELET': {'nome': 'ELETROBRAS', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'EMAE': {'nome': 'EMAE', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'EMBR': {'nome': 'EMBRAER',
          'segmento': 'Material Aeronáutico e de Defesa',
          'setor': 'Bens Industriais',
          'subsetor': 'Material de Transporte'},
 'ENEV': {'nome': 'ENEVA', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'ENGI': {'nome': 'ENERGISA', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'ENJU': {'nome': 'ENJOEI',
          'segmento': 'Programas e S.',
          'setor': 'Tecnologia da Informação',
          'subsetor': 'Softwares e S.'},
 'ENMT': {'nome': 'ENERGISA MT', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'EPAR': {'nome': 'EMBPAR S/A',
          'segmento': 'Material de Transporte',
          'setor': 'Bens Industriais',
          'subsetor': 'Comércio'},
 'EQMA': {'nome': 'EQTLMARANHAO', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'EQPA': {'nome': 'EQTL PARA', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'EQTL': {'nome': 'EQUATORIAL', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'ESPA': {'nome': 'ESPACOLASER',
          'segmento': 'Produtos Diversos',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Comércio Varejista'},
 'ESTR': {'nome': 'ESTRELA',
          'segmento': 'Brinquedos e Jogos',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Viagens e Lazer'},
 'ETER': {'nome': 'ETERNIT',
          'segmento': 'Produtos para Construção',
          'setor': 'Bens Industriais',
          'subsetor': 'Construção e Engenharia'},
 'EUCA': {'nome': 'EUCATEX', 'segmento': 'Madeira', 'setor': 'Materiais Básicos', 'subsetor': 'Madeira e Papel'},
 'EUFA': {'nome': 'EUROFARMA SA',
          'segmento': 'Medicamentos e Outros',
          'setor': 'Saúde',
          'subsetor': 'Comércio e Distribuição'},
 'EVEN': {'nome': 'EVEN', 'segmento': 'Incorporações', 'setor': 'Consumo Cíclico', 'subsetor': 'Construção Civil'},
 'EVTC': {'nome': 'EVERTEC INC',
          'segmento': 'Diversos',
          'setor': 'Financeiro',
          'subsetor': 'Serviços Financeiros Diversos'},
 'EXPB': {'nome': 'EXPERIAN PLC',
          'segmento': 'Programas e S.',
          'setor': 'Tecnologia da Informação',
          'subsetor': 'Softwares e S.'},
 'EZTC': {'nome': 'EZTEC', 'segmento': 'Incorporações', 'setor': 'Consumo Cíclico', 'subsetor': 'Construção Civil'},
 'FESA': {'nome': 'FERBASA',
          'segmento': 'Siderurgia',
          'setor': 'Materiais Básicos',
          'subsetor': 'Siderurgia e Metalurgia'},
 'FHER': {'nome': 'FER HERINGER', 'segmento': 'Fert. e Def.', 'setor': 'Materiais Básicos', 'subsetor': 'Químicos'},
 'FICT': {'nome': 'FICTORALIMEN',
          'segmento': 'Segmento: Outros',
          'setor': 'Setor: Outros',
          'subsetor': 'Subsetor: Outros'},
 'FIEI': {'nome': 'FICA', 'segmento': 'Incorporações', 'setor': 'Consumo Cíclico', 'subsetor': 'Construção Civil'},
 'FIGE': {'nome': 'INVEST BEMGE',
          'segmento': 'Segmento: Outros',
          'setor': 'Setor: Outros',
          'subsetor': 'Subsetor: Outros'},
 'FIQE': {'nome': 'UNIFIQUE', 'segmento': 'Tele.', 'setor': 'Comunicações', 'subsetor': 'Telecomunicações'},
 'FLRY': {'nome': 'FLEURY',
          'segmento': 'Hospitalares, Análises e Diagnósticos',
          'setor': 'Saúde',
          'subsetor': 'Serviços Médico'},
 'FRAS': {'nome': 'FRAS-LE',
          'segmento': 'Material Rodoviário',
          'setor': 'Bens Industriais',
          'subsetor': 'Material de Transporte'},
 'FRIO': {'nome': 'METALFRIO',
          'segmento': 'Máq. e Equip. Industriais',
          'setor': 'Bens Industriais',
          'subsetor': 'Máquinas e Equipamentos'},
 'FRRN': {'nome': 'ALL NORTE',
          'segmento': 'Transp. Ferroviário',
          'setor': 'Bens Industriais',
          'subsetor': 'Transporte'},
 'G2DI': {'nome': 'G2D INVEST',
          'segmento': 'Gestão de Recursos e Investimentos',
          'setor': 'Financeiro',
          'subsetor': 'Serviços Financeiros Diversos'},
 'GEPA': {'nome': 'GER PARANAP', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'GFSA': {'nome': 'GAFISA', 'segmento': 'Incorporações', 'setor': 'Consumo Cíclico', 'subsetor': 'Construção Civil'},
 'GGBR': {'nome': 'GERDAU',
          'segmento': 'Siderurgia',
          'setor': 'Materiais Básicos',
          'subsetor': 'Siderurgia e Metalurgia'},
 'GGPS': {'nome': 'GPS', 'segmento': 'S. Diversos', 'setor': 'Bens Industriais', 'subsetor': 'Serviços Diversos'},
 'GMAT': {'nome': 'GRUPO MATEUS',
          'segmento': 'Alimentos',
          'setor': 'Consumo não Cíclico',
          'subsetor': 'Comércio e Distribuição'},
 'GOAU': {'nome': 'GERDAU MET',
          'segmento': 'Siderurgia',
          'setor': 'Materiais Básicos',
          'subsetor': 'Siderurgia e Metalurgia'},
 'GOLL': {'nome': 'GOL', 'segmento': 'L. Aéreas de Passageiros', 'setor': 'Bens Industriais', 'subsetor': 'Transporte'},
 'GPAR': {'nome': 'CELGPAR', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'GPIV': {'nome': 'GP INVEST',
          'segmento': 'Gestão de Recursos e Investimentos',
          'setor': 'Financeiro',
          'subsetor': 'Serviços Financeiros Diversos'},
 'GRAO': {'nome': 'AGRIBRASIL', 'segmento': 'Agricultura', 'setor': 'Consumo não Cíclico', 'subsetor': 'Agropecuária'},
 'GRND': {'nome': 'GRENDENE',
          'segmento': 'Calçados',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Tecidos, Vestuário e Calçados'},
 'GSHP': {'nome': 'GENERALSHOPP', 'segmento': 'Exploração de Imóveis', 'setor': 'Financeiro', 'subsetor': 'Imóveis'},
 'GUAR': {'nome': 'GUARARAPES',
          'segmento': 'Vestuário e Calçados',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Comércio Varejista'},
 'HAGA': {'nome': 'HAGA S/A',
          'segmento': 'Produtos para Construção',
          'setor': 'Bens Industriais',
          'subsetor': 'Construção e Engenharia'},
 'HAPV': {'nome': 'HAPVIDA',
          'segmento': 'Hospitalares, Análises e Diagnósticos',
          'setor': 'Saúde',
          'subsetor': 'Serviços Médico'},
 'HBOR': {'nome': 'HELBOR', 'segmento': 'Incorporações', 'setor': 'Consumo Cíclico', 'subsetor': 'Construção Civil'},
 'HBRE': {'nome': 'HBR REALTY', 'segmento': 'Exploração de Imóveis', 'setor': 'Financeiro', 'subsetor': 'Imóveis'},
 'HBSA': {'nome': 'HIDROVIAS',
          'segmento': 'Transp. Hidroviário',
          'setor': 'Bens Industriais',
          'subsetor': 'Transporte'},
 'HBTS': {'nome': 'HABITASUL', 'segmento': 'Exploração de Imóveis', 'setor': 'Financeiro', 'subsetor': 'Imóveis'},
 'HETA': {'nome': 'HERCULES',
          'segmento': 'Utensílios Domésticos',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Utilidades Domésticas'},
 'HMOB': {'nome': 'HMOBI S.A',
          'segmento': 'S. de Apoio e Armazenagem',
          'setor': 'Bens Industriais',
          'subsetor': 'Transporte'},
 'HOOT': {'nome': 'HOTEIS OTHON',
          'segmento': 'Hotelaria',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Hoteis e Restaurantes'},
 'HYPE': {'nome': 'HYPERA',
          'segmento': 'Medicamentos e Outros',
          'setor': 'Saúde',
          'subsetor': 'Comércio e Distribuição'},
 'IFCM': {'nome': 'INFRACOMM',
          'segmento': 'Programas e S.',
          'setor': 'Tecnologia da Informação',
          'subsetor': 'Softwares e S.'},
 'IGSN': {'nome': 'IGUA SA', 'segmento': 'Água', 'setor': 'Utilidade Pública', 'subsetor': 'Saneamento'},
 'IGTI': {'nome': 'IGUATEMI S.A', 'segmento': 'Exploração de Imóveis', 'setor': 'Financeiro', 'subsetor': 'Imóveis'},
 'INBR': {'nome': 'INTER CO', 'segmento': 'Bancos', 'setor': 'Financeiro', 'subsetor': 'Intermediários Financeiros'},
 'INEP': {'nome': 'INEPAR',
          'segmento': 'Máq. e Equip. Industriais',
          'setor': 'Bens Industriais',
          'subsetor': 'Máquinas e Equipamentos'},
 'INNC': {'nome': 'INC SA', 'segmento': 'Incorporações', 'setor': 'Consumo Cíclico', 'subsetor': 'Construção Civil'},
 'INTB': {'nome': 'INTELBRAS',
          'segmento': 'Computadores',
          'setor': 'Tecnologia da Informação',
          'subsetor': 'Computadores e Equip.'},
 'IRBR': {'nome': 'IRBBRASIL RE',
          'segmento': 'Resseguradoras',
          'setor': 'Financeiro',
          'subsetor': 'Previdência e Seguros'},
 'ISAE': {'nome': 'ISA ENERGIA', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'ITSA': {'nome': 'ITAUSA', 'segmento': 'Holdings', 'setor': 'Financeiro', 'subsetor': 'Holdings Diversificadas'},
 'ITUB': {'nome': 'ITAUUNIBANCO',
          'segmento': 'Bancos',
          'setor': 'Financeiro',
          'subsetor': 'Intermediários Financeiros'},
 'IVPR': {'nome': 'INVEPAR',
          'segmento': 'S. de Apoio e Armazenagem',
          'setor': 'Bens Industriais',
          'subsetor': 'Transporte'},
 'JALL': {'nome': 'JALLESMACHAD',
          'segmento': 'Açucar e Alcool',
          'setor': 'Consumo não Cíclico',
          'subsetor': 'Alimentos Processados'},
 'JBSS': {'nome': 'JBS N.V.',
          'segmento': 'Carnes e Derivados',
          'setor': 'Consumo não Cíclico',
          'subsetor': 'Alimentos Processados'},
 'JFEN': {'nome': 'JOAO FORTES',
          'segmento': 'Incorporações',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Construção Civil'},
 'JHSF': {'nome': 'JHSF PART', 'segmento': 'Incorporações', 'setor': 'Consumo Cíclico', 'subsetor': 'Construção Civil'},
 'JOPA': {'nome': 'JOSAPAR',
          'segmento': 'Alimentos Diversos',
          'setor': 'Consumo não Cíclico',
          'subsetor': 'Alimentos Processados'},
 'JSLG': {'nome': 'JSL', 'segmento': 'Transp. Rodoviário', 'setor': 'Bens Industriais', 'subsetor': 'Transporte'},
 'KEPL': {'nome': 'KEPLER WEBER',
          'segmento': 'Máq. e Equip. Industriais',
          'setor': 'Bens Industriais',
          'subsetor': 'Máquinas e Equipamentos'},
 'KLAS': {'nome': 'KALLAS', 'segmento': 'Incorporações', 'setor': 'Consumo Cíclico', 'subsetor': 'Construção Civil'},
 'KLBN': {'nome': 'KLABIN S/A',
          'segmento': 'Papel e Celulose',
          'setor': 'Materiais Básicos',
          'subsetor': 'Madeira e Papel'},
 'LAND': {'nome': 'TERRASANTAPA',
          'segmento': 'Agricultura',
          'setor': 'Consumo não Cíclico',
          'subsetor': 'Agropecuária'},
 'LAVV': {'nome': 'LAVVI', 'segmento': 'Incorporações', 'setor': 'Consumo Cíclico', 'subsetor': 'Construção Civil'},
 'LEVE': {'nome': 'METAL LEVE',
          'segmento': 'Auto. e Moto.',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Automóveis e Motocicletas'},
 'LIGH': {'nome': 'LIGHT', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'LIGT': {'nome': 'LIGHT S/A', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'LJQQ': {'nome': 'QUERO-QUERO',
          'segmento': 'Produtos Diversos',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Comércio Varejista'},
 'LLBI': {'nome': 'LE BISCUIT',
          'segmento': 'Produtos Diversos',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Comércio Varejista'},
 'LMED': {'nome': 'LIFEMED', 'segmento': 'Equipamentos Médicos e Hosp.', 'setor': 'Saúde', 'subsetor': 'Equipamentos'},
 'LOGG': {'nome': 'LOG COM PROP', 'segmento': 'Exploração de Imóveis', 'setor': 'Financeiro', 'subsetor': 'Imóveis'},
 'LOGN': {'nome': 'LOG-IN', 'segmento': 'Transp. Hidroviário', 'setor': 'Bens Industriais', 'subsetor': 'Transporte'},
 'LPSB': {'nome': 'LOPES BRASIL',
          'segmento': 'Intermediação Imobiliária',
          'setor': 'Financeiro',
          'subsetor': 'Imóveis'},
 'LREN': {'nome': 'LOJAS RENNER',
          'segmento': 'Vestuário e Calçados',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Comércio Varejista'},
 'LTEL': {'nome': 'LITEL', 'segmento': 'Minerais Metál.', 'setor': 'Materiais Básicos', 'subsetor': 'Mineração'},
 'LTLA': {'nome': 'LITELA', 'segmento': 'Minerais Metál.', 'setor': 'Materiais Básicos', 'subsetor': 'Mineração'},
 'LUPA': {'nome': 'LUPATECH', 'segmento': 'Equip. e Serv.', 'setor': 'Energia', 'subsetor': 'Petro., Gás e Bio.'},
 'LUXM': {'nome': 'TREVISA', 'segmento': 'Transp. Hidroviário', 'setor': 'Bens Industriais', 'subsetor': 'Transporte'},
 'LVTC': {'nome': 'WDC NETWORKS',
          'segmento': 'Programas e S.',
          'setor': 'Tecnologia da Informação',
          'subsetor': 'Softwares e S.'},
 'LWSA': {'nome': 'LWSA',
          'segmento': 'Programas e S.',
          'setor': 'Tecnologia da Informação',
          'subsetor': 'Softwares e S.'},
 'MAPT': {'nome': 'CEMEPE', 'segmento': 'Segmento: Outros', 'setor': 'Setor: Outros', 'subsetor': 'Subsetor: Outros'},
 'MATD': {'nome': 'MATER DEI',
          'segmento': 'Hospitalares, Análises e Diagnósticos',
          'setor': 'Saúde',
          'subsetor': 'Serviços Médico'},
 'MCRJ': {'nome': 'CEPAC - MCRJ', 'segmento': 'Outros títulos', 'setor': 'Financeiro', 'subsetor': 'Títulos'},
 'MDIA': {'nome': 'M.DIASBRANCO',
          'segmento': 'Alimentos Diversos',
          'setor': 'Consumo não Cíclico',
          'subsetor': 'Alimentos Processados'},
 'MDNE': {'nome': 'MOURA DUBEUX',
          'segmento': 'Incorporações',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Construção Civil'},
 'MEAL': {'nome': 'IMC S/A',
          'segmento': 'Restaurante e Similares',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Hoteis e Restaurantes'},
 'MELK': {'nome': 'MELNICK', 'segmento': 'Incorporações', 'setor': 'Consumo Cíclico', 'subsetor': 'Construção Civil'},
 'MERC': {'nome': 'MERC FINANC',
          'segmento': 'Soc. Crédito e Financiamento',
          'setor': 'Financeiro',
          'subsetor': 'Intermediários Financeiros'},
 'MGEL': {'nome': 'MANGELS INDL',
          'segmento': 'Artefatos: Ferro e Aço',
          'setor': 'Materiais Básicos',
          'subsetor': 'Siderurgia e Metalurgia'},
 'MGLU': {'nome': 'MAGAZ LUIZA', 'segmento': 'Eletros.', 'setor': 'Consumo Cíclico', 'subsetor': 'Comércio Varejista'},
 'MILS': {'nome': 'MILLS',
          'segmento': 'Máq. e Equip. Industriais',
          'setor': 'Bens Industriais',
          'subsetor': 'Máquinas e Equipamentos'},
 'MLAS': {'nome': 'MULTILASER',
          'segmento': 'Computadores',
          'setor': 'Tecnologia da Informação',
          'subsetor': 'Computadores e Equip.'},
 'MMAQ': {'nome': 'MINASMAQUINA',
          'segmento': 'Material de Transporte',
          'setor': 'Bens Industriais',
          'subsetor': 'Comércio'},
 'MNDL': {'nome': 'MUNDIAL',
          'segmento': 'Acessórios',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Tecidos, Vestuário e Calçados'},
 'MNPR': {'nome': 'MINUPAR',
          'segmento': 'Carnes e Derivados',
          'setor': 'Consumo não Cíclico',
          'subsetor': 'Alimentos Processados'},
 'MNZC': {'nome': 'MENEZES CORT', 'segmento': 'Exploração de Imóveis', 'setor': 'Financeiro', 'subsetor': 'Imóveis'},
 'MOAR': {'nome': 'MONT ARANHA', 'segmento': 'Holdings', 'setor': 'Financeiro', 'subsetor': 'Holdings Diversificadas'},
 'MOTV': {'nome': 'MOTIVA SA',
          'segmento': 'Exploração de Rodovias',
          'setor': 'Bens Industriais',
          'subsetor': 'Transporte'},
 'MOVI': {'nome': 'MOVIDA', 'segmento': 'Aluguel de carros', 'setor': 'Consumo Cíclico', 'subsetor': 'Diversos'},
 'MRFG': {'nome': 'MARFRIG',
          'segmento': 'Carnes e Derivados',
          'setor': 'Consumo não Cíclico',
          'subsetor': 'Alimentos Processados'},
 'MRSA': {'nome': 'MRS LOGIST',
          'segmento': 'Transp. Ferroviário',
          'setor': 'Bens Industriais',
          'subsetor': 'Transporte'},
 'MRVE': {'nome': 'MRV', 'segmento': 'Incorporações', 'setor': 'Consumo Cíclico', 'subsetor': 'Construção Civil'},
 'MSPA': {'nome': 'MELHOR SP',
          'segmento': 'Papel e Celulose',
          'setor': 'Materiais Básicos',
          'subsetor': 'Madeira e Papel'},
 'MTRE': {'nome': 'MITRE REALTY',
          'segmento': 'Incorporações',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Construção Civil'},
 'MTSA': {'nome': 'METISA',
          'segmento': 'Máq. e Equip. Construção e Agrícolas',
          'setor': 'Bens Industriais',
          'subsetor': 'Máquinas e Equipamentos'},
 'MULT': {'nome': 'MULTIPLAN', 'segmento': 'Exploração de Imóveis', 'setor': 'Financeiro', 'subsetor': 'Imóveis'},
 'MWET': {'nome': 'WETZEL S/A',
          'segmento': 'Material Rodoviário',
          'setor': 'Bens Industriais',
          'subsetor': 'Material de Transporte'},
 'MYPK': {'nome': 'IOCHP-MAXION',
          'segmento': 'Auto. e Moto.',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Automóveis e Motocicletas'},
 'NATU': {'nome': 'NATURA',
          'segmento': 'Prod. de Cuidado Pessoal',
          'setor': 'Consumo não Cíclico',
          'subsetor': 'Cuidado Pessoal e Limpeza'},
 'NEMO': {'nome': 'SUZANO HOLD',
          'segmento': 'Papel e Celulose',
          'setor': 'Materiais Básicos',
          'subsetor': 'Madeira e Papel'},
 'NEOE': {'nome': 'NEOENERGIA', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'NEXP': {'nome': 'NEXPE', 'segmento': 'Intermediação Imobiliária', 'setor': 'Financeiro', 'subsetor': 'Imóveis'},
 'NGRD': {'nome': 'NEOGRID',
          'segmento': 'Programas e S.',
          'setor': 'Tecnologia da Informação',
          'subsetor': 'Softwares e S.'},
 'NORD': {'nome': 'NORDON MET',
          'segmento': 'Máq. e Equip. Industriais',
          'setor': 'Bens Industriais',
          'subsetor': 'Máquinas e Equipamentos'},
 'NRTQ': {'nome': 'NORTCQUIMICA',
          'segmento': 'Medic. e Outros',
          'setor': 'Saúde',
          'subsetor': 'Medicamentos e Outros Produtos'},
 'NUTR': {'nome': 'NUTRIPLANT', 'segmento': 'Fert. e Def.', 'setor': 'Materiais Básicos', 'subsetor': 'Químicos'},
 'ODER': {'nome': 'ODERICH',
          'segmento': 'Alimentos Diversos',
          'setor': 'Consumo não Cíclico',
          'subsetor': 'Alimentos Processados'},
 'ODPV': {'nome': 'ODONTOPREV',
          'segmento': 'Hospitalares, Análises e Diagnósticos',
          'setor': 'Saúde',
          'subsetor': 'Serviços Médico'},
 'OFSA': {'nome': 'OUROFINO S/A',
          'segmento': 'Medic. e Outros',
          'setor': 'Saúde',
          'subsetor': 'Medicamentos e Outros Produtos'},
 'OIBR': {'nome': 'OI', 'segmento': 'Tele.', 'setor': 'Comunicações', 'subsetor': 'Telecomunicações'},
 'ONCO': {'nome': 'ONCOCLINICAS',
          'segmento': 'Hospitalares, Análises e Diagnósticos',
          'setor': 'Saúde',
          'subsetor': 'Serviços Médico'},
 'OPCT': {'nome': 'OCEANPACT', 'segmento': 'Equip. e Serv.', 'setor': 'Energia', 'subsetor': 'Petro., Gás e Bio.'},
 'OPGM': {'nome': 'GAMA PART',
          'segmento': 'Segmento: Outros',
          'setor': 'Setor: Outros',
          'subsetor': 'Subsetor: Outros'},
 'OPSE': {'nome': 'SUDESTE S/A',
          'segmento': 'Segmento: Outros',
          'setor': 'Setor: Outros',
          'subsetor': 'Subsetor: Outros'},
 'OPTS': {'nome': 'SUL 116 PART',
          'segmento': 'Segmento: Outros',
          'setor': 'Setor: Outros',
          'subsetor': 'Subsetor: Outros'},
 'ORVR': {'nome': 'ORIZON', 'segmento': 'Água', 'setor': 'Utilidade Pública', 'subsetor': 'Saneamento'},
 'OSXB': {'nome': 'OSX BRASIL', 'segmento': 'Equip. e Serv.', 'setor': 'Energia', 'subsetor': 'Petro., Gás e Bio.'},
 'PASS': {'nome': 'COMPASS', 'segmento': 'Gás', 'setor': 'Utilidade Pública', 'subsetor': 'Utilidade publ. Gás'},
 'PATI': {'nome': 'PANATLANTICA',
          'segmento': 'Artefatos: Ferro e Aço',
          'setor': 'Materiais Básicos',
          'subsetor': 'Siderurgia e Metalurgia'},
 'PCAR': {'nome': 'P.ACUCAR-CBD',
          'segmento': 'Alimentos',
          'setor': 'Consumo não Cíclico',
          'subsetor': 'Comércio e Distribuição'},
 'PDGR': {'nome': 'PDG REALT', 'segmento': 'Incorporações', 'setor': 'Consumo Cíclico', 'subsetor': 'Construção Civil'},
 'PDTC': {'nome': 'PADTEC',
          'segmento': 'Programas e S.',
          'setor': 'Tecnologia da Informação',
          'subsetor': 'Softwares e S.'},
 'PEAB': {'nome': 'PAR AL BAHIA', 'segmento': 'Exploração de Imóveis', 'setor': 'Financeiro', 'subsetor': 'Imóveis'},
 'PETR': {'nome': 'PETROBRAS',
          'segmento': 'Explo., Refino e Distr.',
          'setor': 'Energia',
          'subsetor': 'Petro., Gás e Bio.'},
 'PETZ': {'nome': 'PETZ',
          'segmento': 'Produtos Diversos',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Comércio Varejista'},
 'PFRM': {'nome': 'PROFARMA',
          'segmento': 'Medicamentos e Outros',
          'setor': 'Saúde',
          'subsetor': 'Comércio e Distribuição'},
 'PGMN': {'nome': 'PAGUE MENOS',
          'segmento': 'Medicamentos e Outros',
          'setor': 'Saúde',
          'subsetor': 'Comércio e Distribuição'},
 'PINE': {'nome': 'PINE', 'segmento': 'Bancos', 'setor': 'Financeiro', 'subsetor': 'Intermediários Financeiros'},
 'PLAS': {'nome': 'PLASCAR PART',
          'segmento': 'Auto. e Moto.',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Automóveis e Motocicletas'},
 'PLPL': {'nome': 'PLANOEPLANO',
          'segmento': 'Incorporações',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Construção Civil'},
 'PLSC': {'nome': 'POLO CAP SEC',
          'segmento': 'Securitizadoras',
          'setor': 'Financeiro',
          'subsetor': 'Securitizadoras de Recebíveis'},
 'PMAM': {'nome': 'PARANAPANEMA',
          'segmento': 'Artefatos: Cobre',
          'setor': 'Materiais Básicos',
          'subsetor': 'Siderurgia e Metalurgia'},
 'PMSP': {'nome': 'CEPAC - PMSP', 'segmento': 'Outros títulos', 'setor': 'Financeiro', 'subsetor': 'Títulos'},
 'PNVL': {'nome': 'DIMED',
          'segmento': 'Medicamentos e Outros',
          'setor': 'Saúde',
          'subsetor': 'Comércio e Distribuição'},
 'POMO': {'nome': 'MARCOPOLO',
          'segmento': 'Material Rodoviário',
          'setor': 'Bens Industriais',
          'subsetor': 'Material de Transporte'},
 'PORT': {'nome': 'WILSON SONS',
          'segmento': 'S. de Apoio e Armazenagem',
          'setor': 'Bens Industriais',
          'subsetor': 'Transporte'},
 'POSI': {'nome': 'POSITIVO TEC',
          'segmento': 'Computadores',
          'setor': 'Tecnologia da Informação',
          'subsetor': 'Computadores e Equip.'},
 'PPAR': {'nome': 'POLPAR', 'segmento': 'Segmento: Outros', 'setor': 'Setor: Outros', 'subsetor': 'Subsetor: Outros'},
 'PPLA': {'nome': 'PPLA',
          'segmento': 'Gestão de Recursos e Investimentos',
          'setor': 'Financeiro',
          'subsetor': 'Serviços Financeiros Diversos'},
 'PRIO': {'nome': 'PETRORIO',
          'segmento': 'Explo., Refino e Distr.',
          'setor': 'Energia',
          'subsetor': 'Petro., Gás e Bio.'},
 'PRMN': {'nome': 'PROMAN', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'PRNR': {'nome': 'PRINER', 'segmento': 'S. Diversos', 'setor': 'Bens Industriais', 'subsetor': 'Serviços Diversos'},
 'PRPT': {'nome': 'PROMPT PART',
          'segmento': 'Segmento: Outros',
          'setor': 'Setor: Outros',
          'subsetor': 'Subsetor: Outros'},
 'PSSA': {'nome': 'PORTO SEGURO',
          'segmento': 'Seguradoras',
          'setor': 'Financeiro',
          'subsetor': 'Previdência e Seguros'},
 'PSVM': {'nome': 'PORTO VM',
          'segmento': 'S. de Apoio e Armazenagem',
          'setor': 'Bens Industriais',
          'subsetor': 'Transporte'},
 'PTBL': {'nome': 'PORTOBELLO',
          'segmento': 'Produtos para Construção',
          'setor': 'Bens Industriais',
          'subsetor': 'Construção e Engenharia'},
 'PTCA': {'nome': 'PRATICA',
          'segmento': 'Máq. e Equip. Industriais',
          'setor': 'Bens Industriais',
          'subsetor': 'Máquinas e Equipamentos'},
 'PTNT': {'nome': 'PETTENATI',
          'segmento': 'Fios e Tecidos',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Tecidos, Vestuário e Calçados'},
 'QUAL': {'nome': 'QUALICORP',
          'segmento': 'Hospitalares, Análises e Diagnósticos',
          'setor': 'Saúde',
          'subsetor': 'Serviços Médico'},
 'QUSW': {'nome': 'QUALITY SOFT',
          'segmento': 'Programas e S.',
          'setor': 'Tecnologia da Informação',
          'subsetor': 'Softwares e S.'},
 'QVQP': {'nome': '524 PARTICIP',
          'segmento': 'Segmento: Outros',
          'setor': 'Setor: Outros',
          'subsetor': 'Subsetor: Outros'},
 'RADL': {'nome': 'RAIADROGASIL',
          'segmento': 'Medicamentos e Outros',
          'setor': 'Saúde',
          'subsetor': 'Comércio e Distribuição'},
 'RAIL': {'nome': 'RUMO S.A.',
          'segmento': 'Transp. Ferroviário',
          'setor': 'Bens Industriais',
          'subsetor': 'Transporte'},
 'RAIZ': {'nome': 'RAIZEN',
          'segmento': 'Explo., Refino e Distr.',
          'setor': 'Energia',
          'subsetor': 'Petro., Gás e Bio.'},
 'RANI': {'nome': 'IRANI', 'segmento': 'Embalagens', 'setor': 'Materiais Básicos', 'subsetor': 'Embalagens'},
 'RAPT': {'nome': 'RANDON PART',
          'segmento': 'Material Rodoviário',
          'setor': 'Bens Industriais',
          'subsetor': 'Material de Transporte'},
 'RBNS': {'nome': 'RODOBENS',
          'segmento': 'Material de Transporte',
          'setor': 'Bens Industriais',
          'subsetor': 'Comércio'},
 'RBRA': {'nome': 'OPEA',
          'segmento': 'Securitizadoras',
          'setor': 'Financeiro',
          'subsetor': 'Securitizadoras de Recebíveis'},
 'RCSL': {'nome': 'RECRUSUL',
          'segmento': 'Material Rodoviário',
          'setor': 'Bens Industriais',
          'subsetor': 'Material de Transporte'},
 'RDNI': {'nome': 'RNI', 'segmento': 'Incorporações', 'setor': 'Consumo Cíclico', 'subsetor': 'Construção Civil'},
 'RDOR': {'nome': 'REDE D OR',
          'segmento': 'Hospitalares, Análises e Diagnósticos',
          'setor': 'Saúde',
          'subsetor': 'Serviços Médico'},
 'REAG': {'nome': 'REAGINVEST',
          'segmento': 'Programas e S.',
          'setor': 'Tecnologia da Informação',
          'subsetor': 'Softwares e S.'},
 'RECV': {'nome': 'PETRORECSA',
          'segmento': 'Explo., Refino e Distr.',
          'setor': 'Energia',
          'subsetor': 'Petro., Gás e Bio.'},
 'REDE': {'nome': 'REDE ENERGIA', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'RENT': {'nome': 'LOCALIZA', 'segmento': 'Aluguel de carros', 'setor': 'Consumo Cíclico', 'subsetor': 'Diversos'},
 'RNEW': {'nome': 'RENOVA', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'ROMI': {'nome': 'ROMI',
          'segmento': 'Máq. e Equip. Industriais',
          'setor': 'Bens Industriais',
          'subsetor': 'Máquinas e Equipamentos'},
 'RPAD': {'nome': 'ALFA HOLDING',
          'segmento': 'Bancos',
          'setor': 'Financeiro',
          'subsetor': 'Intermediários Financeiros'},
 'RPMG': {'nome': 'PET MANGUINH',
          'segmento': 'Explo., Refino e Distr.',
          'setor': 'Energia',
          'subsetor': 'Petro., Gás e Bio.'},
 'RSID': {'nome': 'ROSSI RESID',
          'segmento': 'Incorporações',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Construção Civil'},
 'RSUL': {'nome': 'RIOSULENSE',
          'segmento': 'Material Rodoviário',
          'setor': 'Bens Industriais',
          'subsetor': 'Material de Transporte'},
 'RVEE': {'nome': 'REVEE', 'segmento': 'Eventos e Shows', 'setor': 'Consumo Cíclico', 'subsetor': 'Viagens e Lazer'},
 'SANB': {'nome': 'SANTANDER BR',
          'segmento': 'Bancos',
          'setor': 'Financeiro',
          'subsetor': 'Intermediários Financeiros'},
 'SAPR': {'nome': 'SANEPAR', 'segmento': 'Água', 'setor': 'Utilidade Pública', 'subsetor': 'Saneamento'},
 'SBFG': {'nome': 'GRUPO SBF',
          'segmento': 'Produtos Diversos',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Comércio Varejista'},
 'SBSP': {'nome': 'SABESP', 'segmento': 'Água', 'setor': 'Utilidade Pública', 'subsetor': 'Saneamento'},
 'SCAR': {'nome': 'SAO CARLOS', 'segmento': 'Exploração de Imóveis', 'setor': 'Financeiro', 'subsetor': 'Imóveis'},
 'SEER': {'nome': 'SER EDUCA', 'segmento': 'Serviços Educacionais', 'setor': 'Consumo Cíclico', 'subsetor': 'Diversos'},
 'SEQL': {'nome': 'SEQUOIA LOG',
          'segmento': 'S. Diversos',
          'setor': 'Bens Industriais',
          'subsetor': 'Serviços Diversos'},
 'SGPS': {'nome': 'SPRINGS',
          'segmento': 'Fios e Tecidos',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Tecidos, Vestuário e Calçados'},
 'SHOW': {'nome': 'TIME FOR FUN',
          'segmento': 'Eventos e Shows',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Viagens e Lazer'},
 'SHUL': {'nome': 'SCHULZ',
          'segmento': 'Motores, Compr. e Outros',
          'setor': 'Bens Industriais',
          'subsetor': 'Máquinas e Equipamentos'},
 'SIMH': {'nome': 'SIMPAR', 'segmento': 'Holdings', 'setor': 'Financeiro', 'subsetor': 'Holdings Diversificadas'},
 'SLCE': {'nome': 'SLC AGRICOLA',
          'segmento': 'Agricultura',
          'setor': 'Consumo não Cíclico',
          'subsetor': 'Agropecuária'},
 'SMFT': {'nome': 'SMART FIT',
          'segmento': 'Atividades Esportivas',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Viagens e Lazer'},
 'SMTO': {'nome': 'SAO MARTINHO',
          'segmento': 'Açucar e Alcool',
          'setor': 'Consumo não Cíclico',
          'subsetor': 'Alimentos Processados'},
 'SNSY': {'nome': 'SANSUY',
          'segmento': 'Materiais Diversos',
          'setor': 'Materiais Básicos',
          'subsetor': 'Materiais Diversos'},
 'SOJA': {'nome': 'BOA SAFRA', 'segmento': 'Agricultura', 'setor': 'Consumo não Cíclico', 'subsetor': 'Agropecuária'},
 'SOND': {'nome': 'SONDOTECNICA',
          'segmento': 'Engenharia Consultiva',
          'setor': 'Bens Industriais',
          'subsetor': 'Construção e Engenharia'},
 'SRNA': {'nome': 'SERENA', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'STBP': {'nome': 'SANTOS BRP',
          'segmento': 'S. de Apoio e Armazenagem',
          'setor': 'Bens Industriais',
          'subsetor': 'Transporte'},
 'SUZB': {'nome': 'SUZANO S.A.',
          'segmento': 'Papel e Celulose',
          'setor': 'Materiais Básicos',
          'subsetor': 'Madeira e Papel'},
 'SYNE': {'nome': 'SYN PROP TEC', 'segmento': 'Exploração de Imóveis', 'setor': 'Financeiro', 'subsetor': 'Imóveis'},
 'TAEE': {'nome': 'TAESA', 'segmento': 'Elétrica', 'setor': 'Utilidade Pública', 'subsetor': 'Energia Elétrica'},
 'TASA': {'nome': 'TAURUS ARMAS',
          'segmento': 'Armas e Munições',
          'setor': 'Bens Industriais',
          'subsetor': 'Máquinas e Equipamentos'},
 'TCSA': {'nome': 'TECNISA', 'segmento': 'Incorporações', 'setor': 'Consumo Cíclico', 'subsetor': 'Construção Civil'},
 'TECN': {'nome': 'TECHNOS',
          'segmento': 'Acessórios',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Tecidos, Vestuário e Calçados'},
 'TEGA': {'nome': 'TEGRA INCORP',
          'segmento': 'Incorporações',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Construção Civil'},
 'TELB': {'nome': 'TELEBRAS', 'segmento': 'Tele.', 'setor': 'Comunicações', 'subsetor': 'Telecomunicações'},
 'TEND': {'nome': 'TENDA', 'segmento': 'Incorporações', 'setor': 'Consumo Cíclico', 'subsetor': 'Construção Civil'},
 'TFCO': {'nome': 'TRACK FIELD',
          'segmento': 'Vestuário',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Tecidos, Vestuário e Calçados'},
 'TGMA': {'nome': 'TEGMA', 'segmento': 'Transp. Rodoviário', 'setor': 'Bens Industriais', 'subsetor': 'Transporte'},
 'TIMS': {'nome': 'TIM', 'segmento': 'Tele.', 'setor': 'Comunicações', 'subsetor': 'Telecomunicações'},
 'TKNO': {'nome': 'TEKNO',
          'segmento': 'Artefatos: Ferro e Aço',
          'setor': 'Materiais Básicos',
          'subsetor': 'Siderurgia e Metalurgia'},
 'TOKY': {'nome': 'GRUPO TOKY', 'segmento': 'Móveis', 'setor': 'Consumo Cíclico', 'subsetor': 'Utilidades Domésticas'},
 'TOTS': {'nome': 'TOTVS',
          'segmento': 'Programas e S.',
          'setor': 'Tecnologia da Informação',
          'subsetor': 'Softwares e S.'},
 'TPIS': {'nome': 'TRIUNFO PART',
          'segmento': 'Exploração de Rodovias',
          'setor': 'Bens Industriais',
          'subsetor': 'Transporte'},
 'TRAD': {'nome': 'TC',
          'segmento': 'Programas e S.',
          'setor': 'Tecnologia da Informação',
          'subsetor': 'Softwares e S.'},
 'TRIS': {'nome': 'TRISUL', 'segmento': 'Incorporações', 'setor': 'Consumo Cíclico', 'subsetor': 'Construção Civil'},
 'TTEN': {'nome': '3TENTOS', 'segmento': 'Agricultura', 'setor': 'Consumo não Cíclico', 'subsetor': 'Agropecuária'},
 'TUPY': {'nome': 'TUPY',
          'segmento': 'Material Rodoviário',
          'setor': 'Bens Industriais',
          'subsetor': 'Material de Transporte'},
 'TXRX': {'nome': 'TEX RENAUX',
          'segmento': 'Fios e Tecidos',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Tecidos, Vestuário e Calçados'},
 'UCAS': {'nome': 'UNICASA', 'segmento': 'Móveis', 'setor': 'Consumo Cíclico', 'subsetor': 'Utilidades Domésticas'},
 'UGPA': {'nome': 'ULTRAPAR',
          'segmento': 'Explo., Refino e Distr.',
          'setor': 'Energia',
          'subsetor': 'Petro., Gás e Bio.'},
 'UNIP': {'nome': 'UNIPAR', 'segmento': 'Químicos Diversos', 'setor': 'Materiais Básicos', 'subsetor': 'Químicos'},
 'USIM': {'nome': 'USIMINAS',
          'segmento': 'Siderurgia',
          'setor': 'Materiais Básicos',
          'subsetor': 'Siderurgia e Metalurgia'},
 'VALE': {'nome': 'VALE', 'segmento': 'Minerais Metál.', 'setor': 'Materiais Básicos', 'subsetor': 'Mineração'},
 'VAMO': {'nome': 'VAMOS', 'segmento': 'Aluguel de carros', 'setor': 'Consumo Cíclico', 'subsetor': 'Diversos'},
 'VBBR': {'nome': 'VIBRA', 'segmento': 'Explo., Refino e Distr.', 'setor': 'Energia', 'subsetor': 'Petro., Gás e Bio.'},
 'VITT': {'nome': 'VITTIA', 'segmento': 'Fert. e Def.', 'setor': 'Materiais Básicos', 'subsetor': 'Químicos'},
 'VIVA': {'nome': 'VIVARA S.A.',
          'segmento': 'Acessórios',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Tecidos, Vestuário e Calçados'},
 'VIVR': {'nome': 'VIVER', 'segmento': 'Incorporações', 'setor': 'Consumo Cíclico', 'subsetor': 'Construção Civil'},
 'VIVT': {'nome': 'TELEF BRASIL', 'segmento': 'Tele.', 'setor': 'Comunicações', 'subsetor': 'Telecomunicações'},
 'VLID': {'nome': 'VALID', 'segmento': 'S. Diversos', 'setor': 'Bens Industriais', 'subsetor': 'Serviços Diversos'},
 'VSPT': {'nome': 'FER C ATLANT',
          'segmento': 'Transp. Ferroviário',
          'setor': 'Bens Industriais',
          'subsetor': 'Transporte'},
 'VSTE': {'nome': 'VESTE',
          'segmento': 'Vestuário e Calçados',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Comércio Varejista'},
 'VTRU': {'nome': 'VITRUEDUCA',
          'segmento': 'Serviços Educacionais',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Diversos'},
 'VULC': {'nome': 'VULCABRAS',
          'segmento': 'Calçados',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Tecidos, Vestuário e Calçados'},
 'VVEO': {'nome': 'VIVEO',
          'segmento': 'Medicamentos e Outros',
          'setor': 'Saúde',
          'subsetor': 'Comércio e Distribuição'},
 'WEGE': {'nome': 'WEG',
          'segmento': 'Motores, Compr. e Outros',
          'setor': 'Bens Industriais',
          'subsetor': 'Máquinas e Equipamentos'},
 'WEST': {'nome': 'WESTWING', 'segmento': 'Móveis', 'setor': 'Consumo Cíclico', 'subsetor': 'Utilidades Domésticas'},
 'WHRL': {'nome': 'WHIRLPOOL',
          'segmento': 'Eletrodomésticos',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Utilidades Domésticas'},
 'WIZC': {'nome': 'WIZ CO',
          'segmento': 'Corretoras de Seguros e Resseguros',
          'setor': 'Financeiro',
          'subsetor': 'Previdência e Seguros'},
 'WLMM': {'nome': 'WLM IND COM',
          'segmento': 'Material de Transporte',
          'setor': 'Bens Industriais',
          'subsetor': 'Comércio'},
 'XPBR': {'nome': 'XP INC', 'segmento': 'Diversos', 'setor': 'Financeiro', 'subsetor': 'Serviços Financeiros Diversos'},
 'YDUQ': {'nome': 'YDUQS PART',
          'segmento': 'Serviços Educacionais',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Diversos'},
 'ZAMP': {'nome': 'ZAMP S.A.',
          'segmento': 'Restaurante e Similares',
          'setor': 'Consumo Cíclico',
          'subsetor': 'Hoteis e Restaurantes'}}