# Mapeamento manual inicial baseado na B3 (50 tickers populares como exemplo)
SETOR_MAP = {
    "AZTE": "Petróleo, Gás e Biocombustíveis",
    "BRAV": "Petróleo, Gás e Biocombustíveis",
    "CSAN": "Petróleo, Gás e Biocombustíveis",
    "RPMG": "Petróleo, Gás e Biocombustíveis",
    "PETR": "Petróleo, Gás e Biocombustíveis",
    "RECV": "Petróleo, Gás e Biocombustíveis",
    "PRIO": "Petróleo, Gás e Biocombustíveis",
    "RAIZ": "Petróleo, Gás e Biocombustíveis",
    "UGPA": "Petróleo, Gás e Biocombustíveis",
    "VBBR": "Petróleo, Gás e Biocombustíveis",
    "LUPA": "Petróleo, Gás e Biocombustíveis",
    "OPCT": "Petróleo, Gás e Biocombustíveis",
    "OSXB": "Petróleo, Gás e Biocombustíveis",
    "AURA": "Materiais Básicos",
    "BRAP": "Materiais Básicos",
    "CBAV": "Materiais Básicos",
    "CMIN": "Materiais Básicos",
    "LTEL": "Materiais Básicos",
    "LTLA": "Materiais Básicos",
    "VALE": "Materiais Básicos",
    "FESA": "Materiais Básicos",
    "GGBR": "Materiais Básicos",
    "GOAU": "Materiais Básicos",
    "CSNA": "Materiais Básicos",
    "USIM": "Materiais Básicos",
    "MGEL": "Materiais Básicos",
    "PATI": "Materiais Básicos",
    "TKNO": "Materiais Básicos",
    "PMAM": "Materiais Básicos",
    "BRKM": "Materiais Básicos",
    "DEXP": "Materiais Básicos",
    "FHER": "Materiais Básicos",
    "NUTR": "Materiais Básicos",
    "VITT": "Materiais Básicos",
    "CRPG": "Materiais Básicos",
    "UNIP": "Materiais Básicos",
    "DXCO": "Materiais Básicos",
    "EUCA": "Materiais Básicos",
    "KLBN": "Materiais Básicos",
    "MSPA": "Materiais Básicos",
    "NEMO": "Materiais Básicos",
    "SUZB": "Materiais Básicos",
    "RANI": "Materiais Básicos",
    "SNSY": "Materiais Básicos",
    "ETER": "Bens Industriais",
    "HAGA": "Bens Industriais",
    "PTBL": "Bens Industriais",
    "AZEV": "Bens Industriais",
    "SOND": "Bens Industriais",
    "EMBR": "Bens Industriais",
    "FRAS": "Bens Industriais",
    "POMO": "Bens Industriais",
    "RAPT": "Bens Industriais",
    "RCSL": "Bens Industriais",
    "RSUL": "Bens Industriais",
    "TUPY": "Bens Industriais",
    "MWET": "Bens Industriais",
    "SHUL": "Bens Industriais",
    "WEGE": "Bens Industriais",
    "EALT": "Bens Industriais",
    "AERI": "Bens Industriais",
    "ARML": "Bens Industriais",
    "BDLL": "Bens Industriais",
    "INEP": "Bens Industriais",
    "KEPL": "Bens Industriais",
    "FRIO": "Bens Industriais",
    "MILS": "Bens Industriais",
    "NORD": "Bens Industriais",
    "PTCA": "Bens Industriais",
    "ROMI": "Bens Industriais",
    "MTSA": "Bens Industriais",
    "TASA": "Bens Industriais",
    "AZUL": "Bens Industriais",
    "GOLL": "Bens Industriais",
    "FRRN": "Bens Industriais",
    "VSPT": "Bens Industriais",
    "MRSA": "Bens Industriais",
    "RAIL": "Bens Industriais",
    "HBSA": "Bens Industriais",
    "LOGN": "Bens Industriais",
    "LUXM": "Bens Industriais",
    "JSLG": "Bens Industriais",
    "TGMA": "Bens Industriais",
    "MOTV": "Bens Industriais",
    "CRTE": "Bens Industriais",
    "ECOR": "Bens Industriais",
    "TPIS": "Bens Industriais",
    "AGRU": "Bens Industriais",
    "HMOB": "Bens Industriais",
    "IVPR": "Bens Industriais",
    "PSVM": "Bens Industriais",
    "STBP": "Bens Industriais",
    "PORT": "Bens Industriais",
    "CTAX": "Bens Industriais",
    "BBML": "Bens Industriais",
    "DTCY": "Bens Industriais",
    "ALPK": "Bens Industriais",
    "GGPS": "Bens Industriais",
    "PRNR": "Bens Industriais",
    "SEQL": "Bens Industriais",
    "VLID": "Bens Industriais",
    "EPAR": "Bens Industriais",
    "MMAQ": "Bens Industriais",
    "RBNS": "Bens Industriais",
    "WLMM": "Bens Industriais",
    "TTEN": "Consumo Não Cíclico",
    "GRAO": "Consumo Não Cíclico",
    "AGXY": "Consumo Não Cíclico",
    "APTI": "Consumo Não Cíclico",
    "SOJA": "Consumo Não Cíclico",
    "AGRO": "Consumo Não Cíclico",
    "CTCA": "Consumo Não Cíclico",
    "EGGY": "Consumo Não Cíclico",
    "SLCE": "Consumo Não Cíclico",
    "LAND": "Consumo Não Cíclico",
    "JALL": "Consumo Não Cíclico",
    "SMTO": "Consumo Não Cíclico",
    "BRFS": "Consumo Não Cíclico",
    "BAUH": "Consumo Não Cíclico",
    "JBSS": "Consumo Não Cíclico",
    "MRFG": "Consumo Não Cíclico",
    "BEEF": "Consumo Não Cíclico",
    "MNPR": "Consumo Não Cíclico",
    "CAML": "Consumo Não Cíclico",
    "JOPA": "Consumo Não Cíclico",
    "MDIA": "Consumo Não Cíclico",
    "ODER": "Consumo Não Cíclico",
    "ABEV": "Consumo Não Cíclico",
    "NATU": "Consumo Não Cíclico",
    "BOBR": "Consumo Não Cíclico",
    "ASAI": "Consumo Não Cíclico",
    "CAFR": "Consumo Não Cíclico",
    "GMAT": "Consumo Não Cíclico",
    "PCAR": "Consumo Não Cíclico",
    "AVLL": "Consumo Cíclico",
    "CALI": "Consumo Cíclico",
    "CURY": "Consumo Cíclico",
    "CYRE": "Consumo Cíclico",
    "DIRR": "Consumo Cíclico",
    "EVEN": "Consumo Cíclico",
    "EZTC": "Consumo Cíclico",
    "FIEI": "Consumo Cíclico",
    "GFSA": "Consumo Cíclico",
    "HBOR": "Consumo Cíclico",
    "INNC": "Consumo Cíclico",
    "JHSF": "Consumo Cíclico",
    "JFEN": "Consumo Cíclico",
    "KLAS": "Consumo Cíclico",
    "LAVV": "Consumo Cíclico",
    "MELK": "Consumo Cíclico",
    "MTRE": "Consumo Cíclico",
    "MDNE": "Consumo Cíclico",
    "MRVE": "Consumo Cíclico",
    "PDGR": "Consumo Cíclico",
    "PLPL": "Consumo Cíclico",
    "CCTY": "Consumo Cíclico",
    "RDNI": "Consumo Cíclico",
    "RSID": "Consumo Cíclico",
    "TCSA": "Consumo Cíclico",
    "TEGA": "Consumo Cíclico",
    "TEND": "Consumo Cíclico",
    "TRIS": "Consumo Cíclico",
    "VIVR": "Consumo Cíclico",
    "CEDO": "Consumo Cíclico",
    "CTNM": "Consumo Cíclico",
    "DOHL": "Consumo Cíclico",
    "CATA": "Consumo Cíclico",
    "CTKA": "Consumo Cíclico",
    "PTNT": "Consumo Cíclico",
    "CTSA": "Consumo Cíclico",
    "SGPS": "Consumo Cíclico",
    "TXRX": "Consumo Cíclico",
    "TFCO": "Consumo Cíclico",
    "ALPA": "Consumo Cíclico",
    "CAMB": "Consumo Cíclico",
    "GRND": "Consumo Cíclico",
    "VULC": "Consumo Cíclico",
    "MNDL": "Consumo Cíclico",
    "TECN": "Consumo Cíclico",
    "VIVA": "Consumo Cíclico",
    "WHRL": "Consumo Cíclico",
    "TOKY": "Consumo Cíclico",
    "UCAS": "Consumo Cíclico",
    "WEST": "Consumo Cíclico",
    "HETA": "Consumo Cíclico",
    "AMOB": "Consumo Cíclico",
    "MYPK": "Consumo Cíclico",
    "LEVE": "Consumo Cíclico",
    "PLAS": "Consumo Cíclico",
    "HOOT": "Consumo Cíclico",
    "MEAL": "Consumo Cíclico",
    "ZAMP": "Consumo Cíclico",
    "BMKS": "Consumo Cíclico",
    "ESTR": "Consumo Cíclico",
    "RVEE": "Consumo Cíclico",
    "AHEB": "Consumo Cíclico",
    "SHOW": "Consumo Cíclico",
    "CVCB": "Consumo Cíclico",
    "SMFT": "Consumo Cíclico",
    "ANIM": "Consumo Cíclico",
    "ATED": "Consumo Cíclico",
    "BIED": "Consumo Cíclico",
    "COGN": "Consumo Cíclico",
    "CSED": "Consumo Cíclico",
    "SEER": "Consumo Cíclico",
    "VTRU": "Consumo Cíclico",
    "YDUQ": "Consumo Cíclico",
    "RENT": "Consumo Cíclico",
    "MOVI": "Consumo Cíclico",
    "VAMO": "Consumo Cíclico",
    "DOTZ": "Consumo Cíclico",
    "AZZA": "Consumo Cíclico",
    "CEAB": "Consumo Cíclico",
    "CGRA": "Consumo Cíclico",
    "GUAR": "Consumo Cíclico",
    "AMAR": "Consumo Cíclico",
    "LREN": "Consumo Cíclico",
    "VSTE": "Consumo Cíclico",
    "ALLD": "Consumo Cíclico",
    "BHIA": "Consumo Cíclico",
    "MGLU": "Consumo Cíclico",
    "AMER": "Consumo Cíclico",
    "ESPA": "Consumo Cíclico",
    "SBFG": "Consumo Cíclico",
    "LLBI": "Consumo Cíclico",
    "PETZ": "Consumo Cíclico",
    "LJQQ": "Consumo Cíclico",
    "BIOM": "Saúde",
    "NRTQ": "Saúde",
    "OFSA": "Saúde",
    "AALR": "Saúde",
    "DASA": "Saúde",
    "FLRY": "Saúde",
    "HAPV": "Saúde",
    "MATD": "Saúde",
    "ODPV": "Saúde",
    "ONCO": "Saúde",
    "QUAL": "Saúde",
    "RDOR": "Saúde",
    "BALM": "Saúde",
    "LMED": "Saúde",
    "BLAU": "Saúde",
    "DMVF": "Saúde",
    "PNVL": "Saúde",
    "EUFA": "Saúde",
    "HYPE": "Saúde",
    "PGMN": "Saúde",
    "PFRM": "Saúde",
    "RADL": "Saúde",
    "VVEO": "Saúde",
    "INTB": "Tecnologia da Informação",
    "MLAS": "Tecnologia da Informação",
    "POSI": "Tecnologia da Informação",
    "BMOB": "Tecnologia da Informação",
    "BRQB": "Tecnologia da Informação",
    "ENJU": "Tecnologia da Informação",
    "EXPB": "Tecnologia da Informação",
    "REAG": "Tecnologia da Informação",
    "IFCM": "Tecnologia da Informação",
    "LWSA": "Tecnologia da Informação",
    "CASH": "Tecnologia da Informação",
    "NGRD": "Tecnologia da Informação",
    "PDTC": "Tecnologia da Informação",
    "QUSW": "Tecnologia da Informação",
    "TRAD": "Tecnologia da Informação",
    "TOTS": "Tecnologia da Informação",
    "LVTC": "Tecnologia da Informação",
    "BRST": "Comunicações",
    "DESK": "Comunicações",
    "OIBR": "Comunicações",
    "TELB": "Comunicações",
    "VIVT": "Comunicações",
    "TIMS": "Comunicações",
    "FIQE": "Comunicações",
    "AESO": "Utilidade Pública",
    "AFLT": "Utilidade Pública",
    "ALUP": "Utilidade Pública",
    "CBEE": "Utilidade Pública",
    "AURE": "Utilidade Pública",
    "CEBR": "Utilidade Pública",
    "CEED": "Utilidade Pública",
    "CLSC": "Utilidade Pública",
    "GPAR": "Utilidade Pública",
    "CMIG": "Utilidade Pública",
    "CEEB": "Utilidade Pública",
    "COCE": "Utilidade Pública",
    "COMR": "Utilidade Pública",
    "CPLE": "Utilidade Pública",
    "CPFE": "Utilidade Pública",
    "EKTR": "Utilidade Pública",
    "ELET": "Utilidade Pública",
    "EMAE": "Utilidade Pública",
    "ENGI": "Utilidade Pública",
    "ENMT": "Utilidade Pública",
    "ENEV": "Utilidade Pública",
    "EGIE": "Utilidade Pública",
    "EQPA": "Utilidade Pública",
    "EQMA": "Utilidade Pública",
    "EQTL": "Utilidade Pública",
    "GEPA": "Utilidade Pública",
    "ISAE": "Utilidade Pública",
    "LIGH": "Utilidade Pública",
    "LIGT": "Utilidade Pública",
    "NEOE": "Utilidade Pública",
    "SRNA": "Utilidade Pública",
    "PRMN": "Utilidade Pública",
    "REDE": "Utilidade Pública",
    "RNEW": "Utilidade Pública",
    "TAEE": "Utilidade Pública",
    "AMBP": "Utilidade Pública",
    "CASN": "Utilidade Pública",
    "CSMG": "Utilidade Pública",
    "IGSN": "Utilidade Pública",
    "ORVR": "Utilidade Pública",
    "SBSP": "Utilidade Pública",
    "SAPR": "Utilidade Pública",
    "CEGR": "Utilidade Pública",
    "CGAS": "Utilidade Pública",
    "PASS": "Utilidade Pública",
    "ABCB": "Financeiro",
    "RPAD": "Financeiro",
    "BAZA": "Financeiro",
    "BMGB": "Financeiro",
    "BPAN": "Financeiro",
    "BGIP": "Financeiro",
    "BEES": "Financeiro",
    "BPAR": "Financeiro",
    "BRSR": "Financeiro",
    "BRBI": "Financeiro",
    "BBDC": "Financeiro",
    "BBAS": "Financeiro",
    "BSLI": "Financeiro",
    "BPAC": "Financeiro",
    "INBR": "Financeiro",
    "ITUB": "Financeiro",
    "BMEB": "Financeiro",
    "BMIN": "Financeiro",
    "BNBR": "Financeiro",
    "PINE": "Financeiro",
    "SANB": "Financeiro",
    "MERC": "Financeiro",
    "BSCS": "Financeiro",
    "RBRA": "Financeiro",
    "PLSC": "Financeiro",
    "G2DI": "Financeiro",
    "GPIV": "Financeiro",
    "PPLA": "Financeiro",
    "B3SA": "Financeiro",
    "CSUD": "Financeiro",
    "EFXB": "Financeiro",
    "EVTC": "Financeiro",
    "XPBR": "Financeiro",
    "BBSE": "Financeiro",
    "CXSE": "Financeiro",
    "PSSA": "Financeiro",
    "IRBR": "Financeiro",
    "WIZC": "Financeiro",
    "ALOS": "Financeiro",
    "GSHP": "Financeiro",
    "HBTS": "Financeiro",
    "HBRE": "Financeiro",
    "IGTI": "Financeiro",
    "LOGG": "Financeiro",
    "MNZC": "Financeiro",
    "MULT": "Financeiro",
    "PEAB": "Financeiro",
    "SCAR": "Financeiro",
    "SYNE": "Financeiro",
    "LPSB": "Financeiro",
    "NEXP": "Financeiro",
    "ADMF": "Financeiro",
    "ITSA": "Financeiro",
    "MOAR": "Financeiro",
    "SIMH": "Financeiro",
    "CTBA": "Financeiro",
    "MCRJ": "Financeiro",
    "PMSP": "Financeiro",
    "QVQP": "Outros",
    "BETP": "Outros",
    "MAPT": "Outros",
    "FICT": "Outros",
    "OPGM": "Outros",
    "FIGE": "Outros",
    "PPAR": "Outros",
    "PRPT": "Outros",
    "OPSE": "Outros",
    "OPTS": "Outros",
}
YFINANCE_SECTOR_MAP = {
    "Energy": "Petróleo, Gás e Biocombustíveis",
    "Basic Materials": "Materiais Básicos",
    "Industrials": "Bens Industriais",
    "Consumer Defensive": "Consumo Não Cíclico",
    "Consumer Cyclical": "Consumo Cíclico",
    "Healthcare": "Saúde",
    "Technology": "Tecn paremologia da Informação",
    "Communication Services": "Comunicações",
    "Utilities": "Utilidade Pública",
    "Financial Services": "Financeiro",
    "Real Estate": "Financeiro",
    "Unknown": "Outros",
}
# Lista de setores para inicialização de dicionários
SETORES = [
    "Petróleo, Gás e Biocombustíveis",
    "Materiais Básicos",
    "Bens Industriais",
    "Consumo Não Cíclico",
    "Consumo Cíclico",
    "Saúde",
    "Tecnologia da Informação",
    "Comunicações",
    "Utilidade Pública",
    "Financeiro",
    "Outros",
]
SETORIAL_B3 = {
    "AZTE": {"setor": "Petróleo, Gás e Biocombustíveis", "subsetor": "Petróleo, Gás e Biocombustíveis", "segmento": "Exploração, Refino e Distribuição"},
    "BRAV": {"setor": "Petróleo, Gás e Biocombustíveis", "subsetor": "Petróleo, Gás e Biocombustíveis", "segmento": "Exploração, Refino e Distribuição"},
    "CSAN": {"setor": "Petróleo, Gás e Biocombustíveis", "subsetor": "Petróleo, Gás e Biocombustíveis", "segmento": "Exploração, Refino e Distribuição"},
    "RPMG": {"setor": "Petróleo, Gás e Biocombustíveis", "subsetor": "Petróleo, Gás e Biocombustíveis", "segmento": "Exploração, Refino e Distribuição"},
    "PETR": {"setor": "Petróleo, Gás e Biocombustíveis", "subsetor": "Petróleo, Gás e Biocombustíveis", "segmento": "Exploração, Refino e Distribuição"},
    "RECV": {"setor": "Petróleo, Gás e Biocombustíveis", "subsetor": "Petróleo, Gás e Biocombustíveis", "segmento": "Exploração, Refino e Distribuição"},
    "PRIO": {"setor": "Petróleo, Gás e Biocombustíveis", "subsetor": "Petróleo, Gás e Biocombustíveis", "segmento": "Exploração, Refino e Distribuição"},
    "RAIZ": {"setor": "Petróleo, Gás e Biocombustíveis", "subsetor": "Petróleo, Gás e Biocombustíveis", "segmento": "Exploração, Refino e Distribuição"},
    "UGPA": {"setor": "Petróleo, Gás e Biocombustíveis", "subsetor": "Petróleo, Gás e Biocombustíveis", "segmento": "Exploração, Refino e Distribuição"},
    "VBBR": {"setor": "Petróleo, Gás e Biocombustíveis", "subsetor": "Petróleo, Gás e Biocombustíveis", "segmento": "Exploração, Refino e Distribuição"},
    "LUPA": {"setor": "Petróleo, Gás e Biocombustíveis", "subsetor": "Petróleo, Gás e Biocombustíveis", "segmento": "Equipamentos e Serviços"},
    "OPCT": {"setor": "Petróleo, Gás e Biocombustíveis", "subsetor": "Petróleo, Gás e Biocombustíveis", "segmento": "Equipamentos e Serviços"},
    "OSXB": {"setor": "Petróleo, Gás e Biocombustíveis", "subsetor": "Petróleo, Gás e Biocombustíveis", "segmento": "Equipamentos e Serviços"},
    "AURA": {"setor": "Materiais Básicos", "subsetor": "Mineração", "segmento": "Minerais Metálicos"},
    "BRAP": {"setor": "Materiais Básicos", "subsetor": "Mineração", "segmento": "Minerais Metálicos"},
    "CBAV": {"setor": "Materiais Básicos", "subsetor": "Mineração", "segmento": "Minerais Metálicos"},
    "CMIN": {"setor": "Materiais Básicos", "subsetor": "Mineração", "segmento": "Minerais Metálicos"},
    "LTEL": {"setor": "Materiais Básicos", "subsetor": "Mineração", "segmento": "Minerais Metálicos"},
    "LTLA": {"setor": "Materiais Básicos", "subsetor": "Mineração", "segmento": "Minerais Metálicos"},
    "VALE": {"setor": "Materiais Básicos", "subsetor": "Mineração", "segmento": "Minerais Metálicos"},
    "FESA": {"setor": "Materiais Básicos", "subsetor": "Siderurgia e Metalurgia", "segmento": "Siderurgia"},
    "GGBR": {"setor": "Materiais Básicos", "subsetor": "Siderurgia e Metalurgia", "segmento": "Siderurgia"},
    "GOAU": {"setor": "Materiais Básicos", "subsetor": "Siderurgia e Metalurgia", "segmento": "Siderurgia"},
    "CSNA": {"setor": "Materiais Básicos", "subsetor": "Siderurgia e Metalurgia", "segmento": "Siderurgia"},
    "USIM": {"setor": "Materiais Básicos", "subsetor": "Siderurgia e Metalurgia", "segmento": "Siderurgia"},
    "MGEL": {"setor": "Materiais Básicos", "subsetor": "Siderurgia e Metalurgia", "segmento": "Artefatos de Ferro e Aço"},
    "PATI": {"setor": "Materiais Básicos", "subsetor": "Siderurgia e Metalurgia", "segmento": "Artefatos de Ferro e Aço"},
    "TKNO": {"setor": "Materiais Básicos", "subsetor": "Siderurgia e Metalurgia", "segmento": "Artefatos de Ferro e Aço"},
    "PMAM": {"setor": "Materiais Básicos", "subsetor": "Siderurgia e Metalurgia", "segmento": "Artefatos de Cobre"},
    "BRKM": {"setor": "Materiais Básicos", "subsetor": "Químicos", "segmento": "Petroquímicos"},
    "DEXP": {"setor": "Materiais Básicos", "subsetor": "Químicos", "segmento": "Petroquímicos"},
    "FHER": {"setor": "Materiais Básicos", "subsetor": "Químicos", "segmento": "Fertilizantes e Defensivos"},
    "NUTR": {"setor": "Materiais Básicos", "subsetor": "Químicos", "segmento": "Fertilizantes e Defensivos"},
    "VITT": {"setor": "Materiais Básicos", "subsetor": "Químicos", "segmento": "Fertilizantes e Defensivos"},
    "CRPG": {"setor": "Materiais Básicos", "subsetor": "Químicos", "segmento": "Químicos Diversos"},
    "UNIP": {"setor": "Materiais Básicos", "subsetor": "Químicos", "segmento": "Químicos Diversos"},
    "DXCO": {"setor": "Materiais Básicos", "subsetor": "Madeira e Papel", "segmento": "Madeira"},
    "EUCA": {"setor": "Materiais Básicos", "subsetor": "Madeira e Papel", "segmento": "Madeira"},
    "KLBN": {"setor": "Materiais Básicos", "subsetor": "Madeira e Papel", "segmento": "Papel e Celulose"},
    "MSPA": {"setor": "Materiais Básicos", "subsetor": "Madeira e Papel", "segmento": "Papel e Celulose"},
    "NEMO": {"setor": "Materiais Básicos", "subsetor": "Madeira e Papel", "segmento": "Papel e Celulose"},
    "SUZB": {"setor": "Materiais Básicos", "subsetor": "Madeira e Papel", "segmento": "Papel e Celulose"},
    "RANI": {"setor": "Materiais Básicos", "subsetor": "Embalagens", "segmento": "Embalagens"},
    "SNSY": {"setor": "Materiais Básicos", "subsetor": "Materiais Diversos", "segmento": "Materiais Diversos"},
    "ETER": {"setor": "Bens Industriais", "subsetor": "Construção e Engenharia", "segmento": "Produtos para Construção"},
    "HAGA": {"setor": "Bens Industriais", "subsetor": "Construção e Engenharia", "segmento": "Produtos para Construção"},
    "PTBL": {"setor": "Bens Industriais", "subsetor": "Construção e Engenharia", "segmento": "Produtos para Construção"},
    "AZEV": {"setor": "Bens Industriais", "subsetor": "Construção e Engenharia", "segmento": "Construção Pesada"},
    "SOND": {"setor": "Bens Industriais", "subsetor": "Construção e Engenharia", "segmento": "Engenharia Consultiva"},
    "EMBR": {"setor": "Bens Industriais", "subsetor": "Material de Transporte", "segmento": "Material Aeronáutico e de Defesa"},
    "FRAS": {"setor": "Bens Industriais", "subsetor": "Material de Transporte", "segmento": "Material Rodoviário"},
    "POMO": {"setor": "Bens Industriais", "subsetor": "Material de Transporte", "segmento": "Material Rodoviário"},
    "RAPT": {"setor": "Bens Industriais", "subsetor": "Material de Transporte", "segmento": "Material Rodoviário"},
    "RCSL": {"setor": "Bens Industriais", "subsetor": "Material de Transporte", "segmento": "Material Rodoviário"},
    "RSUL": {"setor": "Bens Industriais", "subsetor": "Material de Transporte", "segmento": "Material Rodoviário"},
    "TUPY": {"setor": "Bens Industriais", "subsetor": "Material de Transporte", "segmento": "Material Rodoviário"},
    "MWET": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Motores, Compressores e Outros"},
    "SHUL": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Motores, Compressores e Outros"},
    "WEGE": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Motores, Compressores e Outros"},
    "EALT": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Máq. e Equip. Industriais"},
    "AERI": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Máq. e Equip. Industriais"},
    "ARML": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Máq. e Equip. Industriais"},
    "BDLL": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Máq. e Equip. Industriais"},
    "INEP": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Máq. e Equip. Industriais"},
    "KEPL": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Máq. e Equip. Industriais"},
    "FRIO": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Máq. e Equip. Industriais"},
    "MILS": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Máq. e Equip. Industriais"},
    "NORD": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Máq. e Equip. Industriais"},
    "PTCA": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Máq. e Equip. Industriais"},
    "ROMI": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Máq. e Equip. Industriais"},
    "MTSA": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Máq. e Equip. Construção e Agrícolas"},
    "TASA": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Armas e Munições"},
    "AZUL": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Linhas Aéreas de Passageiros"},
    "GOLL": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Linhas Aéreas de Passageiros"},
    "FRRN": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Transporte Ferroviário"},
    "VSPT": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Transporte Ferroviário"},
    "MRSA": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Transporte Ferroviário"},
    "RAIL": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Transporte Ferroviário"},
    "HBSA": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Transporte Hidroviário"},
    "LOGN": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Transporte Hidroviário"},
    "LUXM": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Transporte Hidroviário"},
    "JSLG": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Transporte Rodoviário"},
    "TGMA": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Transporte Rodoviário"},
    "MOTV": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Exploração de Rodovias"},
    "CRTE": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Exploração de Rodovias"},
    "ECOR": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Exploração de Rodovias"},
    "TPIS": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Exploração de Rodovias"},
    "AGRU": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Serviços de Apoio e Armazenagem"},
    "HMOB": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Serviços de Apoio e Armazenagem"},
    "IVPR": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Serviços de Apoio e Armazenagem"},
    "PSVM": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Serviços de Apoio e Armazenagem"},
    "STBP": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Serviços de Apoio e Armazenagem"},
    "PORT": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Serviços de Apoio e Armazenagem"},
    "CTAX": {"setor": "Bens Industriais", "subsetor": "Serviços Diversos", "segmento": "Serviços Diversos"},
    "BBML": {"setor": "Bens Industriais", "subsetor": "Serviços Diversos", "segmento": "Serviços Diversos"},
    "DTCY": {"setor": "Bens Industriais", "subsetor": "Serviços Diversos", "segmento": "Serviços Diversos"},
    "ALPK": {"setor": "Bens Industriais", "subsetor": "Serviços Diversos", "segmento": "Serviços Diversos"},
    "GGPS": {"setor": "Bens Industriais", "subsetor": "Serviços Diversos", "segmento": "Serviços Diversos"},
    "PRNR": {"setor": "Bens Industriais", "subsetor": "Serviços Diversos", "segmento": "Serviços Diversos"},
    "SEQL": {"setor": "Bens Industriais", "subsetor": "Serviços Diversos", "segmento": "Serviços Diversos"},
    "VLID": {"setor": "Bens Industriais", "subsetor": "Serviços Diversos", "segmento": "Serviços Diversos"},
    "EPAR": {"setor": "Bens Industriais", "subsetor": "Comércio", "segmento": "Material de Transporte"},
    "MMAQ": {"setor": "Bens Industriais", "subsetor": "Comércio", "segmento": "Material de Transporte"},
    "RBNS": {"setor": "Bens Industriais", "subsetor": "Comércio", "segmento": "Material de Transporte"},
    "WLMM": {"setor": "Bens Industriais", "subsetor": "Comércio", "segmento": "Material de Transporte"},
    "TTEN": {"setor": "Consumo Não Cíclico", "subsetor": "Agropecuária", "segmento": "Agricultura"},
    "GRAO": {"setor": "Consumo Não Cíclico", "subsetor": "Agropecuária", "segmento": "Agricultura"},
    "AGXY": {"setor": "Consumo Não Cíclico", "subsetor": "Agropecuária", "segmento": "Agricultura"},
    "APTI": {"setor": "Consumo Não Cíclico", "subsetor": "Agropecuária", "segmento": "Agricultura"},
    "SOJA": {"setor": "Consumo Não Cíclico", "subsetor": "Agropecuária", "segmento": "Agricultura"},
    "AGRO": {"setor": "Consumo Não Cíclico", "subsetor": "Agropecuária", "segmento": "Agricultura"},
    "CTCA": {"setor": "Consumo Não Cíclico", "subsetor": "Agropecuária", "segmento": "Agricultura"},
    "EGGY": {"setor": "Consumo Não Cíclico", "subsetor": "Agropecuária", "segmento": "Agricultura"},
    "SLCE": {"setor": "Consumo Não Cíclico", "subsetor": "Agropecuária", "segmento": "Agricultura"},
    "LAND": {"setor": "Consumo Não Cíclico", "subsetor": "Agropecuária", "segmento": "Agricultura"},
    "JALL": {"setor": "Consumo Não Cíclico", "subsetor": "Alimentos Processados", "segmento": "Açúcar e Álcool"},
    "SMTO": {"setor": "Consumo Não Cíclico", "subsetor": "Alimentos Processados", "segmento": "Açúcar e Álcool"},
    "BRFS": {"setor": "Consumo Não Cíclico", "subsetor": "Alimentos Processados", "segmento": "Carnes e Derivados"},
    "BAUH": {"setor": "Consumo Não Cíclico", "subsetor": "Alimentos Processados", "segmento": "Carnes e Derivados"},
    "JBSS": {"setor": "Consumo Não Cíclico", "subsetor": "Alimentos Processados", "segmento": "Carnes e Derivados"},
    "MRFG": {"setor": "Consumo Não Cíclico", "subsetor": "Alimentos Processados", "segmento": "Carnes e Derivados"},
    "BEEF": {"setor": "Consumo Não Cíclico", "subsetor": "Alimentos Processados", "segmento": "Carnes e Derivados"},
    "MNPR": {"setor": "Consumo Não Cíclico", "subsetor": "Alimentos Processados", "segmento": "Carnes e Derivados"},
    "CAML": {"setor": "Consumo Não Cíclico", "subsetor": "Alimentos Processados", "segmento": "Alimentos Diversos"},
    "JOPA": {"setor": "Consumo Não Cíclico", "subsetor": "Alimentos Processados", "segmento": "Alimentos Diversos"},
    "MDIA": {"setor": "Consumo Não Cíclico", "subsetor": "Alimentos Processados", "segmento": "Alimentos Diversos"},
    "ODER": {"setor": "Consumo Não Cíclico", "subsetor": "Alimentos Processados", "segmento": "Alimentos Diversos"},
    "ABEV": {"setor": "Consumo Não Cíclico", "subsetor": "Bebidas", "segmento": "Cervejas e Refrigerantes"},
    "NATU": {"setor": "Consumo Não Cíclico", "subsetor": "Produtos de Uso Pessoal e Limpeza", "segmento": "Produtos de Uso Pessoal"},
    "BOBR": {"setor": "Consumo Não Cíclico", "subsetor": "Produtos de Uso Pessoal e Limpeza", "segmento": "Produtos de Limpeza"},
    "ASAI": {"setor": "Consumo Não Cíclico", "subsetor": "Comércio e Distribuição", "segmento": "Alimentos"},
    "CAFR": {"setor": "Consumo Não Cíclico", "subsetor": "Comércio e Distribuição", "segmento": "Alimentos"},
    "GMAT": {"setor": "Consumo Não Cíclico", "subsetor": "Comércio e Distribuição", "segmento": "Alimentos"},
    "PCAR": {"setor": "Consumo Não Cíclico", "subsetor": "Comércio e Distribuição", "segmento": "Alimentos"},
    "AVLL": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "CALI": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "CURY": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "CYRE": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "DIRR": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "EVEN": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "EZTC": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "FIEI": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "GFSA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "HBOR": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "INNC": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "JHSF": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "JFEN": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "KLAS": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "LAVV": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "MELK": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "MTRE": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "MDNE": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "MRVE": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "PDGR": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "PLPL": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "CCTY": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Intermediação Imobiliária"},
    "RDNI": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Intermediação Imobiliária"},
    "RSID": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Intermediação Imobiliária"},
    "TCSA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Intermediação Imobiliária"},
    "TEGA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Intermediação Imobiliária"},
    "TEND": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Intermediação Imobiliária"},
    "TRIS": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Intermediação Imobiliária"},
    "VIVR": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Intermediação Imobiliária"},
    "CEDO": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Fios e Tecidos"},
    "CTNM": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Fios e Tecidos"},
    "DOHL": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Fios e Tecidos"},
    "CATA": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Vestuário"},
    "CTKA": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Vestuário"},
    "PTNT": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Vestuário"},
    "CTSA": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Vestuário"},
    "SGPS": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Vestuário"},
    "TXRX": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Vestuário"},
    "TFCO": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Vestuário"},
    "ALPA": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Calçados"},
    "CAMB": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Calçados"},
    "GRND": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Calçados"},
    "VULC": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Calçados"},
    "MNDL": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Acessórios"},
    "TECN": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Acessórios"},
    "VIVA": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Acessórios"},
    "WHRL": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Acessórios"},
    "TOKY": {"setor": "Consumo Cíclico", "subsetor": "Automóveis e Motocicletas", "segmento": "Automóveis e Motocicletas"},
    "UCAS": {"setor": "Consumo Cíclico", "subsetor": "Automóveis e Motocicletas", "segmento": "Automóveis e Motocicletas"},
    "WEST": {"setor": "Consumo Cíclico", "subsetor": "Automóveis e Motocicletas", "segmento": "Automóveis e Motocicletas"},
    "HETA": {"setor": "Consumo Cíclico", "subsetor": "Automóveis e Motocicletas", "segmento": "Peças e Acessórios"},
    "AMOB": {"setor": "Consumo Cíclico", "subsetor": "Automóveis e Motocicletas", "segmento": "Peças e Acessórios"},
    "MYPK": {"setor": "Consumo Cíclico", "subsetor": "Automóveis e Motocicletas", "segmento": "Peças e Acessórios"},
    "LEVE": {"setor": "Consumo Cíclico", "subsetor": "Automóveis e Motocicletas", "segmento": "Peças e Acessórios"},
    "PLAS": {"setor": "Consumo Cíclico", "subsetor": "Automóveis e Motocicletas", "segmento": "Peças e Acessórios"},
    "HOOT": {"setor": "Consumo Cíclico", "subsetor": "Hoteis e Restaurantes", "segmento": "Restaurantes"},
    "MEAL": {"setor": "Consumo Cíclico", "subsetor": "Hoteis e Restaurantes", "segmento": "Restaurantes"},
    "ZAMP": {"setor": "Consumo Cíclico", "subsetor": "Hoteis e Restaurantes", "segmento": "Restaurantes"},
    "BMKS": {"setor": "Consumo Cíclico", "subsetor": "Hoteis e Restaurantes", "segmento": "Hotéis"},
    "ESTR": {"setor": "Consumo Cíclico", "subsetor": "Hoteis e Restaurantes", "segmento": "Hotéis"},
    "RVEE": {"setor": "Consumo Cíclico", "subsetor": "Hoteis e Restaurantes", "segmento": "Hotéis"},
    "AHEB": {"setor": "Consumo Cíclico", "subsetor": "Diversos", "segmento": "Atividades Esportivas"},
    "SHOW": {"setor": "Consumo Cíclico", "subsetor": "Diversos", "segmento": "Atividades Esportivas"},
    "CVCB": {"setor": "Consumo Cíclico", "subsetor": "Diversos", "segmento": "Viagens e Turismo"},
    "SMFT": {"setor": "Consumo Cíclico", "subsetor": "Diversos", "segmento": "Viagens e Turismo"},
    "ANIM": {"setor": "Consumo Cíclico", "subsetor": "Diversos", "segmento": "Programas de Fidelização"},
    "ATED": {"setor": "Consumo Cíclico", "subsetor": "Diversos", "segmento": "Educação"},
    "BIED": {"setor": "Consumo Cíclico", "subsetor": "Diversos", "segmento": "Educação"},
    "COGN": {"setor": "Consumo Cíclico", "subsetor": "Diversos", "segmento": "Educação"},
    "CSED": {"setor": "Consumo Cíclico", "subsetor": "Diversos", "segmento": "Educação"},
    "SEER": {"setor": "Consumo Cíclico", "subsetor": "Diversos", "segmento": "Educação"},
    "VTRU": {"setor": "Consumo Cíclico", "subsetor": "Diversos", "segmento": "Educação"},
    "YDUQ": {"setor": "Consumo Cíclico", "subsetor": "Diversos", "segmento": "Educação"},
    "RENT": {"setor": "Consumo Cíclico", "subsetor": "Aluguel de carros", "segmento": "Aluguel de Carros"},
    "MOVI": {"setor": "Consumo Cíclico", "subsetor": "Aluguel de carros", "segmento": "Aluguel de Carros"},
    "VAMO": {"setor": "Consumo Cíclico", "subsetor": "Aluguel de carros", "segmento": "Aluguel de Carros"},
    "DOTZ": {"setor": "Consumo Cíclico", "subsetor": "Programas de Fidelidade", "segmento": "Programas de Fidelidade"},
    "AZZA": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Tecidos, Vestuário e Calçados"},
    "CEAB": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Tecidos, Vestuário e Calçados"},
    "CGRA": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Tecidos, Vestuário e Calçados"},
    "GUAR": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Tecidos, Vestuário e Calçados"},
    "AMAR": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Tecidos, Vestuário e Calçados"},
    "LREN": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Tecidos, Vestuário e Calçados"},
    "VSTE": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Tecidos, Vestuário e Calçados"},
    "ALLD": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Eletrodomésticos"},
    "BHIA": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Eletrodomésticos"},
    "MGLU": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Eletrodomésticos"},
    "AMER": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Eletrodomésticos"},
    "ESPA": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Eletrodomésticos"},
    "SBFG": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Eletrodomésticos"},
    "LLBI": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Móveis"},
    "PETZ": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Produtos Diversos"},
    "LJQQ": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Produtos Diversos"},
    "BIOM": {"setor": "Saúde", "subsetor": "Medicamentos e Outros Produtos", "segmento": "Medicamentos e Outros Produtos"},
    "NRTQ": {"setor": "Saúde", "subsetor": "Medicamentos e Outros Produtos", "segmento": "Medicamentos e Outros Produtos"},
    "OFSA": {"setor": "Saúde", "subsetor": "Medicamentos e Outros Produtos", "segmento": "Medicamentos e Outros Produtos"},
    "AALR": {"setor": "Saúde", "subsetor": "Serviços Médico - Hospitalares, Análises e Diagnósticos", "segmento": "Análises e Diagnósticos"},
    "DASA": {"setor": "Saúde", "subsetor": "Serviços Médico - Hospitalares, Análises e Diagnósticos", "segmento": "Análises e Diagnósticos"},
    "FLRY": {"setor": "Saúde", "subsetor": "Serviços Médico - Hospitalares, Análises e Diagnósticos", "segmento": "Análises e Diagnósticos"},
    "HAPV": {"setor": "Saúde", "subsetor": "Serviços Médico - Hospitalares, Análises e Diagnósticos", "segmento": "Análises e Diagnósticos"},
    "MATD": {"setor": "Saúde", "subsetor": "Serviços Médico - Hospitalares, Análises e Diagnósticos", "segmento": "Análises e Diagnósticos"},
    "ODPV": {"setor": "Saúde", "subsetor": "Serviços Médico - Hospitalares, Análises e Diagnósticos", "segmento": "Análises e Diagnósticos"},
    "ONCO": {"setor": "Saúde", "subsetor": "Serviços Médico - Hospitalares, Análises e Diagnósticos", "segmento": "Análises e Diagnósticos"},
    "QUAL": {"setor": "Saúde", "subsetor": "Serviços Médico - Hospitalares, Análises e Diagnósticos", "segmento": "Serviços Médico - Hospitalares"},
    "RDOR": {"setor": "Saúde", "subsetor": "Serviços Médico - Hospitalares, Análises e Diagnósticos", "segmento": "Serviços Médico - Hospitalares"},
    "BALM": {"setor": "Saúde", "subsetor": "Comércio e Distribuição", "segmento": "Medicamentos"},
    "LMED": {"setor": "Saúde", "subsetor": "Comércio e Distribuição", "segmento": "Medicamentos"},
    "BLAU": {"setor": "Saúde", "subsetor": "Medicamentos e Outros Produtos", "segmento": "Medicamentos e Outros Produtos"},
    "DMVF": {"setor": "Saúde", "subsetor": "Medicamentos e Outros Produtos", "segmento": "Medicamentos e Outros Produtos"},
    "PNVL": {"setor": "Saúde", "subsetor": "Medicamentos e Outros Produtos", "segmento": "Medicamentos e Outros Produtos"},
    "EUFA": {"setor": "Saúde", "subsetor": "Medicamentos e Outros Produtos", "segmento": "Medicamentos e Outros Produtos"},
    "HYPE": {"setor": "Saúde", "subsetor": "Medicamentos e Outros Produtos", "segmento": "Medicamentos e Outros Produtos"},
    "PGMN": {"setor": "Saúde", "subsetor": "Medicamentos e Outros Produtos", "segmento": "Medicamentos e Outros Produtos"},
    "PFRM": {"setor": "Saúde", "subsetor": "Medicamentos e Outros Produtos", "segmento": "Medicamentos e Outros Produtos"},
    "RADL": {"setor": "Saúde", "subsetor": "Medicamentos e Outros Produtos", "segmento": "Medicamentos e Outros Produtos"},
    "VVEO": {"setor": "Saúde", "subsetor": "Medicamentos e Outros Produtos", "segmento": "Medicamentos e Outros Produtos"},
    "INTB": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "MLAS": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "POSI": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "BMOB": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "BRQB": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "ENJU": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "EXPB": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "REAG": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "IFCM": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "LWSA": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "CASH": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "NGRD": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "PDTC": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "QUSW": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "TRAD": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "TOTS": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "LVTC": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "BRST": {"setor": "Comunicações", "subsetor": "Telecomunicações", "segmento": "Telecomunicações"},
    "DESK": {"setor": "Comunicações", "subsetor": "Telecomunicações", "segmento": "Telecomunicações"},
    "OIBR": {"setor": "Comunicações", "subsetor": "Telecomunicações", "segmento": "Telecomunicações"},
    "TELB": {"setor": "Comunicações", "subsetor": "Telecomunicações", "segmento": "Telecomunicações"},
    "VIVT": {"setor": "Comunicações", "subsetor": "Telecomunicações", "segmento": "Telecomunicações"},
    "TIMS": {"setor": "Comunicações", "subsetor": "Telecomunicações", "segmento": "Telecomunicações"},
    "FIQE": {"setor": "Comunicações", "subsetor": "Telecomunicações", "segmento": "Telecomunicações"},
    "AESO": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "AFLT": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "ALUP": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "CBEE": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "AURE": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "CEBR": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "CEED": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "CLSC": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "GPAR": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "CMIG": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "CEEB": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "COCE": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "COMR": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "CPLE": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "CPFE": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "EKTR": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "ELET": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "EMAE": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "ENGI": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "ENMT": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "ENEV": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "EGIE": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "EQPA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "EQMA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "EQTL": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "GEPA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "ISAE": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "LIGH": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "LIGT": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "NEOE": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "SRNA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "PRMN": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "REDE": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "RNEW": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "TAEE": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "AMBP": {"setor": "Utilidade Pública", "subsetor": "Água e Saneamento", "segmento": "Água e Saneamento"},
    "CASN": {"setor": "Utilidade Pública", "subsetor": "Água e Saneamento", "segmento": "Água e Saneamento"},
    "CSMG": {"setor": "Utilidade Pública", "subsetor": "Água e Saneamento", "segmento": "Água e Saneamento"},
    "IGSN": {"setor": "Utilidade Pública", "subsetor": "Água e Saneamento", "segmento": "Água e Saneamento"},
    "ORVR": {"setor": "Utilidade Pública", "subsetor": "Água e Saneamento", "segmento": "Água e Saneamento"},
    "SBSP": {"setor": "Utilidade Pública", "subsetor": "Água e Saneamento", "segmento": "Água e Saneamento"},
    "SAPR": {"setor": "Utilidade Pública", "subsetor": "Água e Saneamento", "segmento": "Água e Saneamento"},
    "CEGR": {"setor": "Utilidade Pública", "subsetor": "Gás", "segmento": "Gás"},
    "CGAS": {"setor": "Utilidade Pública", "subsetor": "Gás", "segmento": "Gás"},
    "PASS": {"setor": "Utilidade Pública", "subsetor": "Gás", "segmento": "Gás"},
    "ABCB": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "RPAD": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "BAZA": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "BMGB": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "BPAN": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "BGIP": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "BEES": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "BPAR": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "BRSR": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "BRBI": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "BBDC": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "BBAS": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "BSLI": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "BPAC": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "INBR": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "ITUB": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "BMEB": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "BMIN": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "BNBR": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "PINE": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "SANB": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "MERC": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Financeiras Diversas"},
    "BSCS": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Financeiras Diversas"},
    "RBRA": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Financeiras Diversas"},
    "PLSC": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Financeiras Diversas"},
    "G2DI": {"setor": "Financeiro", "subsetor": "Gestão de Recursos e Investimentos", "segmento": "Gestão de Recursos e Investimentos"},
    "GPIV": {"setor": "Financeiro", "subsetor": "Gestão de Recursos e Investimentos", "segmento": "Gestão de Recursos e Investimentos"},
    "PPLA": {"setor": "Financeiro", "subsetor": "Gestão de Recursos e Investimentos", "segmento": "Gestão de Recursos e Investimentos"},
    "B3SA": {"setor": "Financeiro", "subsetor": "Serviços Financeiros Diversos", "segmento": "Bolsa de Valores"},
    "CSUD": {"setor": "Financeiro", "subsetor": "Serviços Financeiros Diversos", "segmento": "Cartões de Crédito"},
    "EFXB": {"setor": "Financeiro", "subsetor": "Serviços Financeiros Diversos", "segmento": "Cartões de Crédito"},
    "EVTC": {"setor": "Financeiro", "subsetor": "Serviços Financeiros Diversos", "segmento": "Cartões de Crédito"},
    "XPBR": {"setor": "Financeiro", "subsetor": "Serviços Financeiros Diversos", "segmento": "Corretoras de Valores e Commodities"},
    "BBSE": {"setor": "Financeiro", "subsetor": "Previdência e Seguros", "segmento": "Seguradoras"},
    "CXSE": {"setor": "Financeiro", "subsetor": "Previdência e Seguros", "segmento": "Seguradoras"},
    "PSSA": {"setor": "Financeiro", "subsetor": "Previdência e Seguros", "segmento": "Seguradoras"},
    "IRBR": {"setor": "Financeiro", "subsetor": "Previdência e Seguros", "segmento": "Resseguradoras"},
    "WIZC": {"setor": "Financeiro", "subsetor": "Previdência e Seguros", "segmento": "Corretores de Seguros"},
    "ALOS": {"setor": "Financeiro", "subsetor": "Exploração de Imóveis", "segmento": "Exploração de Imóveis"},
    "GSHP": {"setor": "Financeiro", "subsetor": "Exploração de Imóveis", "segmento": "Shopping Centers"},
    "HBTS": {"setor": "Financeiro", "subsetor": "Exploração de Imóveis", "segmento": "Exploração de Imóveis"},
    "HBRE": {"setor": "Financeiro", "subsetor": "Exploração de Imóveis", "segmento": "Exploração de Imóveis"},
    "IGBR": {"setor": "Financeiro", "subsetor": "Exploração de Imóveis", "segmento": "Exploração de Imóveis"},
    "IGTI": {"setor": "Financeiro", "subsetor": "Exploração de Imóveis", "segmento": "Exploração de Imóveis"},
    "LOGG": {"setor": "Financeiro", "subsetor": "Exploração de Imóveis", "segmento": "Exploração de Imóveis"},
    "MNZC": {"setor": "Financeiro", "subsetor": "Exploração de Imóveis", "segmento": "Exploração de Imóveis"},    
    "MULT": {"setor": "Financeiro", "subsetor": "Exploração de Imóveis", "segmento": "Exploração de Imóveis"},
    "PEAB": {"setor": "Financeiro", "subsetor": "Exploração de Imóveis", "segmento": "Exploração de Imóveis"},
    "SCAR": {"setor": "Financeiro", "subsetor": "Exploração de Imóveis", "segmento": "Exploração de Imóveis"},
    "SYNE": {"setor": "Financeiro", "subsetor": "Exploração de Imóveis", "segmento": "Exploração de Imóveis"},
    "LPSB": {"setor": "Financeiro", "subsetor": "Exploração de Imóveis", "segmento": "Intermediação Imobiliária"},
    "NEXP": {"setor": "Financeiro", "subsetor": "Exploração de Imóveis", "segmento": "Intermediação Imobiliária"},
    "ADMF": {"setor": "Financeiro", "subsetor": "Holdings Diversificadas", "segmento": "Holdings Diversificadas"},
    "ITSA": {"setor": "Financeiro", "subsetor": "Holdings Diversificadas", "segmento": "Holdings Diversificadas"},
    "MOAR": {"setor": "Financeiro", "subsetor": "Holdings Diversificadas", "segmento": "Holdings Diversificadas"},
    "SIMH": {"setor": "Financeiro", "subsetor": "Holdings Diversificadas", "segmento": "Holdings Diversificadas"},
    "CTBA": {"setor": "Financeiro", "subsetor": "Outros Títulos", "segmento": "Outros Títulos"},
    "MCRJ": {"setor": "Financeiro", "subsetor": "Outros Títulos", "segmento": "Outros Títulos"},
    "PMSP": {"setor": "Financeiro", "subsetor": "Outros Títulos", "segmento": "Outros Títulos"},
    "QVQP": {"setor": "Outros", "subsetor": "Outros", "segmento": "Outros"},
    "BETP": {"setor": "Outros", "subsetor": "Outros", "segmento": "Outros"},
    "MAPT": {"setor": "Outros", "subsetor": "Outros", "segmento": "Outros"},
    "FICT": {"setor": "Outros", "subsetor": "Outros", "segmento": "Outros"},
    "OPGM": {"setor": "Outros", "subsetor": "Outros", "segmento": "Outros"},
    "FIGE": {"setor": "Outros", "subsetor": "Outros", "segmento": "Outros"},
    "PPAR": {"setor": "Outros", "subsetor": "Outros", "segmento": "Outros"},
    "PRPT": {"setor": "Outros", "subsetor": "Outros", "segmento": "Outros"},
    "OPSE": {"setor": "Outros", "subsetor": "Outros", "segmento": "Outros"},
    "OPTS": {"setor": "Outros", "subsetor": "Outros", "segmento": "Outros"},
}