# Mapeamento manual inicial baseado na B3 (50 tickers populares como exemplo)
SETOR_MAP = {
    "AZTE.SA": "Petróleo, Gás e Biocombustíveis",
    "BRAV.SA": "Petróleo, Gás e Biocombustíveis",
    "CSAN.SA": "Petróleo, Gás e Biocombustíveis",
    "RPMG.SA": "Petróleo, Gás e Biocombustíveis",
    "PETR.SA": "Petróleo, Gás e Biocombustíveis",
    "RECV.SA": "Petróleo, Gás e Biocombustíveis",
    "PRIO.SA": "Petróleo, Gás e Biocombustíveis",
    "RAIZ.SA": "Petróleo, Gás e Biocombustíveis",
    "UGPA.SA": "Petróleo, Gás e Biocombustíveis",
    "VBBR.SA": "Petróleo, Gás e Biocombustíveis",
    "LUPA.SA": "Petróleo, Gás e Biocombustíveis",
    "OPCT.SA": "Petróleo, Gás e Biocombustíveis",
    "OSXB.SA": "Petróleo, Gás e Biocombustíveis",
    "AURA.SA": "Materiais Básicos",
    "BRAP.SA": "Materiais Básicos",
    "CBAV.SA": "Materiais Básicos",
    "CMIN.SA": "Materiais Básicos",
    "LTEL.SA": "Materiais Básicos",
    "LTLA.SA": "Materiais Básicos",
    "VALE.SA": "Materiais Básicos",
    "FESA.SA": "Materiais Básicos",
    "GGBR.SA": "Materiais Básicos",
    "GOAU.SA": "Materiais Básicos",
    "CSNA.SA": "Materiais Básicos",
    "USIM.SA": "Materiais Básicos",
    "MGEL.SA": "Materiais Básicos",
    "PATI.SA": "Materiais Básicos",
    "TKNO.SA": "Materiais Básicos",
    "PMAM.SA": "Materiais Básicos",
    "BRKM.SA": "Materiais Básicos",
    "DEXP.SA": "Materiais Básicos",
    "FHER.SA": "Materiais Básicos",
    "NUTR.SA": "Materiais Básicos",
    "VITT.SA": "Materiais Básicos",
    "CRPG.SA": "Materiais Básicos",
    "UNIP.SA": "Materiais Básicos",
    "DXCO.SA": "Materiais Básicos",
    "EUCA.SA": "Materiais Básicos",
    "KLBN.SA": "Materiais Básicos",
    "MSPA.SA": "Materiais Básicos",
    "NEMO.SA": "Materiais Básicos",
    "SUZB.SA": "Materiais Básicos",
    "RANI.SA": "Materiais Básicos",
    "SNSY.SA": "Materiais Básicos",
    "ETER.SA": "Bens Industriais",
    "HAGA.SA": "Bens Industriais",
    "PTBL.SA": "Bens Industriais",
    "AZEV.SA": "Bens Industriais",
    "SOND.SA": "Bens Industriais",
    "EMBR.SA": "Bens Industriais",
    "FRAS.SA": "Bens Industriais",
    "POMO.SA": "Bens Industriais",
    "RAPT.SA": "Bens Industriais",
    "RCSL.SA": "Bens Industriais",
    "RSUL.SA": "Bens Industriais",
    "TUPY.SA": "Bens Industriais",
    "MWET.SA": "Bens Industriais",
    "SHUL.SA": "Bens Industriais",
    "WEGE.SA": "Bens Industriais",
    "EALT.SA": "Bens Industriais",
    "AERI.SA": "Bens Industriais",
    "ARML.SA": "Bens Industriais",
    "BDLL.SA": "Bens Industriais",
    "INEP.SA": "Bens Industriais",
    "KEPL.SA": "Bens Industriais",
    "FRIO.SA": "Bens Industriais",
    "MILS.SA": "Bens Industriais",
    "NORD.SA": "Bens Industriais",
    "PTCA.SA": "Bens Industriais",
    "ROMI.SA": "Bens Industriais",
    "MTSA.SA": "Bens Industriais",
    "TASA.SA": "Bens Industriais",
    "AZUL.SA": "Bens Industriais",
    "GOLL.SA": "Bens Industriais",
    "FRRN.SA": "Bens Industriais",
    "VSPT.SA": "Bens Industriais",
    "MRSA.SA": "Bens Industriais",
    "RAIL.SA": "Bens Industriais",
    "HBSA.SA": "Bens Industriais",
    "LOGN.SA": "Bens Industriais",
    "LUXM.SA": "Bens Industriais",
    "JSLG.SA": "Bens Industriais",
    "TGMA.SA": "Bens Industriais",
    "MOTV.SA": "Bens Industriais",
    "CRTE.SA": "Bens Industriais",
    "ECOR.SA": "Bens Industriais",
    "TPIS.SA": "Bens Industriais",
    "AGRU.SA": "Bens Industriais",
    "HMOB.SA": "Bens Industriais",
    "IVPR.SA": "Bens Industriais",
    "PSVM.SA": "Bens Industriais",
    "STBP.SA": "Bens Industriais",
    "PORT.SA": "Bens Industriais",
    "CTAX.SA": "Bens Industriais",
    "BBML.SA": "Bens Industriais",
    "DTCY.SA": "Bens Industriais",
    "ALPK.SA": "Bens Industriais",
    "GGPS.SA": "Bens Industriais",
    "PRNR.SA": "Bens Industriais",
    "SEQL.SA": "Bens Industriais",
    "VLID.SA": "Bens Industriais",
    "EPAR.SA": "Bens Industriais",
    "MMAQ.SA": "Bens Industriais",
    "RBNS.SA": "Bens Industriais",
    "WLMM.SA": "Bens Industriais",
    "TTEN.SA": "Consumo Não Cíclico",
    "GRAO.SA": "Consumo Não Cíclico",
    "AGXY.SA": "Consumo Não Cíclico",
    "APTI.SA": "Consumo Não Cíclico",
    "SOJA.SA": "Consumo Não Cíclico",
    "AGRO.SA": "Consumo Não Cíclico",
    "CTCA.SA": "Consumo Não Cíclico",
    "EGGY.SA": "Consumo Não Cíclico",
    "SLCE.SA": "Consumo Não Cíclico",
    "LAND.SA": "Consumo Não Cíclico",
    "JALL.SA": "Consumo Não Cíclico",
    "SMTO.SA": "Consumo Não Cíclico",
    "BRFS.SA": "Consumo Não Cíclico",
    "BAUH.SA": "Consumo Não Cíclico",
    "JBSS.SA": "Consumo Não Cíclico",
    "MRFG.SA": "Consumo Não Cíclico",
    "BEEF.SA": "Consumo Não Cíclico",
    "MNPR.SA": "Consumo Não Cíclico",
    "CAML.SA": "Consumo Não Cíclico",
    "JOPA.SA": "Consumo Não Cíclico",
    "MDIA.SA": "Consumo Não Cíclico",
    "ODER.SA": "Consumo Não Cíclico",
    "ABEV.SA": "Consumo Não Cíclico",
    "NATU.SA": "Consumo Não Cíclico",
    "BOBR.SA": "Consumo Não Cíclico",
    "ASAI.SA": "Consumo Não Cíclico",
    "CAFR.SA": "Consumo Não Cíclico",
    "GMAT.SA": "Consumo Não Cíclico",
    "PCAR.SA": "Consumo Não Cíclico",
    "AVLL.SA": "Consumo Cíclico",
    "CALI.SA": "Consumo Cíclico",
    "CURY.SA": "Consumo Cíclico",
    "CYRE.SA": "Consumo Cíclico",
    "DIRR.SA": "Consumo Cíclico",
    "EVEN.SA": "Consumo Cíclico",
    "EZTC.SA": "Consumo Cíclico",
    "FIEI.SA": "Consumo Cíclico",
    "GFSA.SA": "Consumo Cíclico",
    "HBOR.SA": "Consumo Cíclico",
    "INNC.SA": "Consumo Cíclico",
    "JHSF.SA": "Consumo Cíclico",
    "JFEN.SA": "Consumo Cíclico",
    "KLAS.SA": "Consumo Cíclico",
    "LAVV.SA": "Consumo Cíclico",
    "MELK.SA": "Consumo Cíclico",
    "MTRE.SA": "Consumo Cíclico",
    "MDNE.SA": "Consumo Cíclico",
    "MRVE.SA": "Consumo Cíclico",
    "PDGR.SA": "Consumo Cíclico",
    "PLPL.SA": "Consumo Cíclico",
    "CCTY.SA": "Consumo Cíclico",
    "RDNI.SA": "Consumo Cíclico",
    "RSID.SA": "Consumo Cíclico",
    "TCSA.SA": "Consumo Cíclico",
    "TEGA.SA": "Consumo Cíclico",
    "TEND.SA": "Consumo Cíclico",
    "TRIS.SA": "Consumo Cíclico",
    "VIVR.SA": "Consumo Cíclico",
    "CEDO.SA": "Consumo Cíclico",
    "CTNM.SA": "Consumo Cíclico",
    "DOHL.SA": "Consumo Cíclico",
    "CATA.SA": "Consumo Cíclico",
    "CTKA.SA": "Consumo Cíclico",
    "PTNT.SA": "Consumo Cíclico",
    "CTSA.SA": "Consumo Cíclico",
    "SGPS.SA": "Consumo Cíclico",
    "TXRX.SA": "Consumo Cíclico",
    "TFCO.SA": "Consumo Cíclico",
    "ALPA.SA": "Consumo Cíclico",
    "CAMB.SA": "Consumo Cíclico",
    "GRND.SA": "Consumo Cíclico",
    "VULC.SA": "Consumo Cíclico",
    "MNDL.SA": "Consumo Cíclico",
    "TECN.SA": "Consumo Cíclico",
    "VIVA.SA": "Consumo Cíclico",
    "WHRL.SA": "Consumo Cíclico",
    "TOKY.SA": "Consumo Cíclico",
    "UCAS.SA": "Consumo Cíclico",
    "WEST.SA": "Consumo Cíclico",
    "HETA.SA": "Consumo Cíclico",
    "AMOB.SA": "Consumo Cíclico",
    "MYPK.SA": "Consumo Cíclico",
    "LEVE.SA": "Consumo Cíclico",
    "PLAS.SA": "Consumo Cíclico",
    "HOOT.SA": "Consumo Cíclico",
    "MEAL.SA": "Consumo Cíclico",
    "ZAMP.SA": "Consumo Cíclico",
    "BMKS.SA": "Consumo Cíclico",
    "ESTR.SA": "Consumo Cíclico",
    "RVEE.SA": "Consumo Cíclico",
    "AHEB.SA": "Consumo Cíclico",
    "SHOW.SA": "Consumo Cíclico",
    "CVCB.SA": "Consumo Cíclico",
    "SMFT.SA": "Consumo Cíclico",
    "ANIM.SA": "Consumo Cíclico",
    "ATED.SA": "Consumo Cíclico",
    "BIED.SA": "Consumo Cíclico",
    "COGN.SA": "Consumo Cíclico",
    "CSED.SA": "Consumo Cíclico",
    "SEER.SA": "Consumo Cíclico",
    "VTRU.SA": "Consumo Cíclico",
    "YDUQ.SA": "Consumo Cíclico",
    "RENT.SA": "Consumo Cíclico",
    "MOVI.SA": "Consumo Cíclico",
    "VAMO.SA": "Consumo Cíclico",
    "DOTZ.SA": "Consumo Cíclico",
    "AZZA.SA": "Consumo Cíclico",
    "CEAB.SA": "Consumo Cíclico",
    "CGRA.SA": "Consumo Cíclico",
    "GUAR.SA": "Consumo Cíclico",
    "AMAR.SA": "Consumo Cíclico",
    "LREN.SA": "Consumo Cíclico",
    "VSTE.SA": "Consumo Cíclico",
    "ALLD.SA": "Consumo Cíclico",
    "BHIA.SA": "Consumo Cíclico",
    "MGLU.SA": "Consumo Cíclico",
    "AMER.SA": "Consumo Cíclico",
    "ESPA.SA": "Consumo Cíclico",
    "SBFG.SA": "Consumo Cíclico",
    "LLBI.SA": "Consumo Cíclico",
    "PETZ.SA": "Consumo Cíclico",
    "LJQQ.SA": "Consumo Cíclico",
    "BIOM.SA": "Saúde",
    "NRTQ.SA": "Saúde",
    "OFSA.SA": "Saúde",
    "AALR.SA": "Saúde",
    "DASA.SA": "Saúde",
    "FLRY.SA": "Saúde",
    "HAPV.SA": "Saúde",
    "MATD.SA": "Saúde",
    "ODPV.SA": "Saúde",
    "ONCO.SA": "Saúde",
    "QUAL.SA": "Saúde",
    "RDOR.SA": "Saúde",
    "BALM.SA": "Saúde",
    "LMED.SA": "Saúde",
    "BLAU.SA": "Saúde",
    "DMVF.SA": "Saúde",
    "PNVL.SA": "Saúde",
    "EUFA.SA": "Saúde",
    "HYPE.SA": "Saúde",
    "PGMN.SA": "Saúde",
    "PFRM.SA": "Saúde",
    "RADL.SA": "Saúde",
    "VVEO.SA": "Saúde",
    "INTB.SA": "Tecnologia da Informação",
    "MLAS.SA": "Tecnologia da Informação",
    "POSI.SA": "Tecnologia da Informação",
    "BMOB.SA": "Tecnologia da Informação",
    "BRQB.SA": "Tecnologia da Informação",
    "ENJU.SA": "Tecnologia da Informação",
    "EXPB.SA": "Tecnologia da Informação",
    "REAG.SA": "Tecnologia da Informação",
    "IFCM.SA": "Tecnologia da Informação",
    "LWSA.SA": "Tecnologia da Informação",
    "CASH.SA": "Tecnologia da Informação",
    "NGRD.SA": "Tecnologia da Informação",
    "PDTC.SA": "Tecnologia da Informação",
    "QUSW.SA": "Tecnologia da Informação",
    "TRAD.SA": "Tecnologia da Informação",
    "TOTS.SA": "Tecnologia da Informação",
    "LVTC.SA": "Tecnologia da Informação",
    "BRST.SA": "Comunicações",
    "DESK.SA": "Comunicações",
    "OIBR.SA": "Comunicações",
    "TELB.SA": "Comunicações",
    "VIVT.SA": "Comunicações",
    "TIMS.SA": "Comunicações",
    "FIQE.SA": "Comunicações",
    "AESO.SA": "Utilidade Pública",
    "AFLT.SA": "Utilidade Pública",
    "ALUP.SA": "Utilidade Pública",
    "CBEE.SA": "Utilidade Pública",
    "AURE.SA": "Utilidade Pública",
    "CEBR.SA": "Utilidade Pública",
    "CEED.SA": "Utilidade Pública",
    "CLSC.SA": "Utilidade Pública",
    "GPAR.SA": "Utilidade Pública",
    "CMIG.SA": "Utilidade Pública",
    "CEEB.SA": "Utilidade Pública",
    "COCE.SA": "Utilidade Pública",
    "COMR.SA": "Utilidade Pública",
    "CPLE.SA": "Utilidade Pública",
    "CPFE.SA": "Utilidade Pública",
    "EKTR.SA": "Utilidade Pública",
    "ELET.SA": "Utilidade Pública",
    "EMAE.SA": "Utilidade Pública",
    "ENGI.SA": "Utilidade Pública",
    "ENMT.SA": "Utilidade Pública",
    "ENEV.SA": "Utilidade Pública",
    "EGIE.SA": "Utilidade Pública",
    "EQPA.SA": "Utilidade Pública",
    "EQMA.SA": "Utilidade Pública",
    "EQTL.SA": "Utilidade Pública",
    "GEPA.SA": "Utilidade Pública",
    "ISAE.SA": "Utilidade Pública",
    "LIGH.SA": "Utilidade Pública",
    "LIGT.SA": "Utilidade Pública",
    "NEOE.SA": "Utilidade Pública",
    "SRNA.SA": "Utilidade Pública",
    "PRMN.SA": "Utilidade Pública",
    "REDE.SA": "Utilidade Pública",
    "RNEW.SA": "Utilidade Pública",
    "TAEE.SA": "Utilidade Pública",
    "AMBP.SA": "Utilidade Pública",
    "CASN.SA": "Utilidade Pública",
    "CSMG.SA": "Utilidade Pública",
    "IGSN.SA": "Utilidade Pública",
    "ORVR.SA": "Utilidade Pública",
    "SBSP.SA": "Utilidade Pública",
    "SAPR.SA": "Utilidade Pública",
    "CEGR.SA": "Utilidade Pública",
    "CGAS.SA": "Utilidade Pública",
    "PASS.SA": "Utilidade Pública",
    "ABCB.SA": "Financeiro",
    "RPAD.SA": "Financeiro",
    "BAZA.SA": "Financeiro",
    "BMGB.SA": "Financeiro",
    "BPAN.SA": "Financeiro",
    "BGIP.SA": "Financeiro",
    "BEES.SA": "Financeiro",
    "BPAR.SA": "Financeiro",
    "BRSR.SA": "Financeiro",
    "BRBI.SA": "Financeiro",
    "BBDC.SA": "Financeiro",
    "BBAS.SA": "Financeiro",
    "BSLI.SA": "Financeiro",
    "BPAC.SA": "Financeiro",
    "INBR.SA": "Financeiro",
    "ITUB.SA": "Financeiro",
    "BMEB.SA": "Financeiro",
    "BMIN.SA": "Financeiro",
    "BNBR.SA": "Financeiro",
    "PINE.SA": "Financeiro",
    "SANB.SA": "Financeiro",
    "MERC.SA": "Financeiro",
    "BSCS.SA": "Financeiro",
    "RBRA.SA": "Financeiro",
    "PLSC.SA": "Financeiro",
    "G2DI.SA": "Financeiro",
    "GPIV.SA": "Financeiro",
    "PPLA.SA": "Financeiro",
    "B3SA.SA": "Financeiro",
    "CSUD.SA": "Financeiro",
    "EFXB.SA": "Financeiro",
    "EVTC.SA": "Financeiro",
    "XPBR.SA": "Financeiro",
    "BBSE.SA": "Financeiro",
    "CXSE.SA": "Financeiro",
    "PSSA.SA": "Financeiro",
    "IRBR.SA": "Financeiro",
    "WIZC.SA": "Financeiro",
    "ALOS.SA": "Financeiro",
    "GSHP.SA": "Financeiro",
    "HBTS.SA": "Financeiro",
    "HBRE.SA": "Financeiro",
    "IGTI.SA": "Financeiro",
    "LOGG.SA": "Financeiro",
    "MNZC.SA": "Financeiro",
    "MULT.SA": "Financeiro",
    "PEAB.SA": "Financeiro",
    "SCAR.SA": "Financeiro",
    "SYNE.SA": "Financeiro",
    "LPSB.SA": "Financeiro",
    "NEXP.SA": "Financeiro",
    "ADMF.SA": "Financeiro",
    "ITSA.SA": "Financeiro",
    "MOAR.SA": "Financeiro",
    "SIMH.SA": "Financeiro",
    "CTBA.SA": "Financeiro",
    "MCRJ.SA": "Financeiro",
    "PMSP.SA": "Financeiro",
    "QVQP.SA": "Outros",
    "BETP.SA": "Outros",
    "MAPT.SA": "Outros",
    "FICT.SA": "Outros",
    "OPGM.SA": "Outros",
    "FIGE.SA": "Outros",
    "PPAR.SA": "Outros",
    "PRPT.SA": "Outros",
    "OPSE.SA": "Outros",
    "OPTS.SA": "Outros",
}
YFINANCE_SECTOR_MAP = {
    "Energy": "Petróleo, Gás e Biocombustíveis",
    "Basic Materials": "Materiais Básicos",
    "Industrials": "Bens Industriais",
    "Consumer Defensive": "Consumo Não Cíclico",
    "Consumer Cyclical": "Consumo Cíclico",
    "Healthcare": "Saúde",
    "Technology": "Tecn paremologia da Informação",
    "Communication Services": "Comunicações",
    "Utilities": "Utilidade Pública",
    "Financial Services": "Financeiro",
    "Real Estate": "Financeiro",
    "Unknown": "Outros",
}
# Lista de setores para inicialização de dicionários
SETORES = [
    "Petróleo, Gás e Biocombustíveis",
    "Materiais Básicos",
    "Bens Industriais",
    "Consumo Não Cíclico",
    "Consumo Cíclico",
    "Saúde",
    "Tecnologia da Informação",
    "Comunicações",
    "Utilidade Pública",
    "Financeiro",
    "Outros",
]
SETORIAL_B3 = {
    "AZTE.SA": {"setor": "Petróleo, Gás e Biocombustíveis", "subsetor": "Petróleo, Gás e Biocombustíveis", "segmento": "Exploração, Refino e Distribuição"},
    "BRAV.SA": {"setor": "Petróleo, Gás e Biocombustíveis", "subsetor": "Petróleo, Gás e Biocombustíveis", "segmento": "Exploração, Refino e Distribuição"},
    "CSAN.SA": {"setor": "Petróleo, Gás e Biocombustíveis", "subsetor": "Petróleo, Gás e Biocombustíveis", "segmento": "Exploração, Refino e Distribuição"},
    "RPMG.SA": {"setor": "Petróleo, Gás e Biocombustíveis", "subsetor": "Petróleo, Gás e Biocombustíveis", "segmento": "Exploração, Refino e Distribuição"},
    "PETR.SA": {"setor": "Petróleo, Gás e Biocombustíveis", "subsetor": "Petróleo, Gás e Biocombustíveis", "segmento": "Exploração, Refino e Distribuição"},
    "RECV.SA": {"setor": "Petróleo, Gás e Biocombustíveis", "subsetor": "Petróleo, Gás e Biocombustíveis", "segmento": "Exploração, Refino e Distribuição"},
    "PRIO.SA": {"setor": "Petróleo, Gás e Biocombustíveis", "subsetor": "Petróleo, Gás e Biocombustíveis", "segmento": "Exploração, Refino e Distribuição"},
    "RAIZ.SA": {"setor": "Petróleo, Gás e Biocombustíveis", "subsetor": "Petróleo, Gás e Biocombustíveis", "segmento": "Exploração, Refino e Distribuição"},
    "UGPA.SA": {"setor": "Petróleo, Gás e Biocombustíveis", "subsetor": "Petróleo, Gás e Biocombustíveis", "segmento": "Exploração, Refino e Distribuição"},
    "VBBR.SA": {"setor": "Petróleo, Gás e Biocombustíveis", "subsetor": "Petróleo, Gás e Biocombustíveis", "segmento": "Exploração, Refino e Distribuição"},
    "LUPA.SA": {"setor": "Petróleo, Gás e Biocombustíveis", "subsetor": "Equipamentos e Serviços", "segmento": "Equipamentos e Serviços"},
    "OPCT.SA": {"setor": "Petróleo, Gás e Biocombustíveis", "subsetor": "Equipamentos e Serviços", "segmento": "Equipamentos e Serviços"},
    "OSXB.SA": {"setor": "Petróleo, Gás e Biocombustíveis", "subsetor": "Equipamentos e Serviços", "segmento": "Equipamentos e Serviços"},
    "AURA.SA": {"setor": "Materiais Básicos", "subsetor": "Mineração", "segmento": "Minerais Metálicos"},
    "BRAP.SA": {"setor": "Materiais Básicos", "subsetor": "Mineração", "segmento": "Minerais Metálicos"},
    "CBAV.SA": {"setor": "Materiais Básicos", "subsetor": "Mineração", "segmento": "Minerais Metálicos"},
    "CMIN.SA": {"setor": "Materiais Básicos", "subsetor": "Mineração", "segmento": "Minerais Metálicos"},
    "LTEL.SA": {"setor": "Materiais Básicos", "subsetor": "Mineração", "segmento": "Minerais Metálicos"},
    "LTLA.SA": {"setor": "Materiais Básicos", "subsetor": "Mineração", "segmento": "Minerais Metálicos"},
    "VALE.SA": {"setor": "Materiais Básicos", "subsetor": "Mineração", "segmento": "Minerais Metálicos"},
    "FESA.SA": {"setor": "Materiais Básicos", "subsetor": "Siderurgia e Metalurgia", "segmento": "Siderurgia"},
    "GGBR.SA": {"setor": "Materiais Básicos", "subsetor": "Siderurgia e Metalurgia", "segmento": "Siderurgia"},
    "GOAU.SA": {"setor": "Materiais Básicos", "subsetor": "Siderurgia e Metalurgia", "segmento": "Siderurgia"},
    "CSNA.SA": {"setor": "Materiais Básicos", "subsetor": "Siderurgia e Metalurgia", "segmento": "Siderurgia"},
    "USIM.SA": {"setor": "Materiais Básicos", "subsetor": "Siderurgia e Metalurgia", "segmento": "Siderurgia"},
    "MGEL.SA": {"setor": "Materiais Básicos", "subsetor": "Siderurgia e Metalurgia", "segmento": "Artefatos de Ferro e Aço"},
    "PATI.SA": {"setor": "Materiais Básicos", "subsetor": "Siderurgia e Metalurgia", "segmento": "Artefatos de Ferro e Aço"},
    "TKNO.SA": {"setor": "Materiais Básicos", "subsetor": "Siderurgia e Metalurgia", "segmento": "Artefatos de Ferro e Aço"},
    "PMAM.SA": {"setor": "Materiais Básicos", "subsetor": "Siderurgia e Metalurgia", "segmento": "Artefatos de Cobre"},
    "BRKM.SA": {"setor": "Materiais Básicos", "subsetor": "Químicos", "segmento": "Petroquímicos"},
    "DEXP.SA": {"setor": "Materiais Básicos", "subsetor": "Químicos", "segmento": "Petroquímicos"},
    "FHER.SA": {"setor": "Materiais Básicos", "subsetor": "Químicos", "segmento": "Fertilizantes e Defensivos"},
    "NUTR.SA": {"setor": "Materiais Básicos", "subsetor": "Químicos", "segmento": "Fertilizantes e Defensivos"},
    "VITT.SA": {"setor": "Materiais Básicos", "subsetor": "Químicos", "segmento": "Fertilizantes e Defensivos"},
    "CRPG.SA": {"setor": "Materiais Básicos", "subsetor": "Químicos", "segmento": "Químicos Diversos"},
    "UNIP.SA": {"setor": "Materiais Básicos", "subsetor": "Químicos", "segmento": "Químicos Diversos"},
    "DXCO.SA": {"setor": "Materiais Básicos", "subsetor": "Madeira e Papel", "segmento": "Madeira"},
    "EUCA.SA": {"setor": "Materiais Básicos", "subsetor": "Madeira e Papel", "segmento": "Madeira"},
    "KLBN.SA": {"setor": "Materiais Básicos", "subsetor": "Madeira e Papel", "segmento": "Papel e Celulose"},
    "MSPA.SA": {"setor": "Materiais Básicos", "subsetor": "Madeira e Papel", "segmento": "Papel e Celulose"},
    "NEMO.SA": {"setor": "Materiais Básicos", "subsetor": "Madeira e Papel", "segmento": "Papel e Celulose"},
    "SUZB.SA": {"setor": "Materiais Básicos", "subsetor": "Madeira e Papel", "segmento": "Papel e Celulose"},
    "RANI.SA": {"setor": "Materiais Básicos", "subsetor": "Embalagens", "segmento": "Embalagens"},
    "SNSY.SA": {"setor": "Materiais Básicos", "subsetor": "Materiais Diversos", "segmento": "Materiais Diversos"},
    "ETER.SA": {"setor": "Bens Industriais", "subsetor": "Construção e Engenharia", "segmento": "Produtos para Construção"},
    "HAGA.SA": {"setor": "Bens Industriais", "subsetor": "Construção e Engenharia", "segmento": "Produtos para Construção"},
    "PTBL.SA": {"setor": "Bens Industriais", "subsetor": "Construção e Engenharia", "segmento": "Produtos para Construção"},
    "AZEV.SA": {"setor": "Bens Industriais", "subsetor": "Construção e Engenharia", "segmento": "Construção Pesada"},
    "SOND.SA": {"setor": "Bens Industriais", "subsetor": "Construção e Engenharia", "segmento": "Engenharia Consultiva"},
    "EMBR.SA": {"setor": "Bens Industriais", "subsetor": "Material de Transporte", "segmento": "Material Aeronáutico e de Defesa"},
    "FRAS.SA": {"setor": "Bens Industriais", "subsetor": "Material de Transporte", "segmento": "Material Rodoviário"},
    "POMO.SA": {"setor": "Bens Industriais", "subsetor": "Material de Transporte", "segmento": "Material Rodoviário"},
    "RAPT.SA": {"setor": "Bens Industriais", "subsetor": "Material de Transporte", "segmento": "Material Rodoviário"},
    "RCSL.SA": {"setor": "Bens Industriais", "subsetor": "Material de Transporte", "segmento": "Material Rodoviário"},
    "RSUL.SA": {"setor": "Bens Industriais", "subsetor": "Material de Transporte", "segmento": "Material Rodoviário"},
    "TUPY.SA": {"setor": "Bens Industriais", "subsetor": "Material de Transporte", "segmento": "Material Rodoviário"},
    "MWET.SA": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Motores, Compressores e Outros"},
    "SHUL.SA": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Motores, Compressores e Outros"},
    "WEGE.SA": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Motores, Compressores e Outros"},
    "EALT.SA": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Máq. e Equip. Industriais"},
    "AERI.SA": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Máq. e Equip. Industriais"},
    "ARML.SA": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Máq. e Equip. Industriais"},
    "BDLL.SA": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Máq. e Equip. Industriais"},
    "INEP.SA": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Máq. e Equip. Industriais"},
    "KEPL.SA": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Máq. e Equip. Industriais"},
    "FRIO.SA": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Máq. e Equip. Industriais"},
    "MILS.SA": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Máq. e Equip. Industriais"},
    "NORD.SA": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Máq. e Equip. Industriais"},
    "PTCA.SA": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Máq. e Equip. Industriais"},
    "ROMI.SA": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Máq. e Equip. Industriais"},
    "MTSA.SA": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Máq. e Equip. Construção e Agrícolas"},
    "TASA.SA": {"setor": "Bens Industriais", "subsetor": "Máquinas e Equipamentos", "segmento": "Armas e Munições"},
    "AZUL.SA": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Linhas Aéreas de Passageiros"},
    "GOLL.SA": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Linhas Aéreas de Passageiros"},
    "FRRN.SA": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Transporte Ferroviário"},
    "VSPT.SA": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Transporte Ferroviário"},
    "MRSA.SA": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Transporte Ferroviário"},
    "RAIL.SA": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Transporte Ferroviário"},
    "HBSA.SA": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Transporte Hidroviário"},
    "LOGN.SA": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Transporte Hidroviário"},
    "LUXM.SA": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Transporte Hidroviário"},
    "JSLG.SA": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Transporte Rodoviário"},
    "TGMA.SA": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Transporte Rodoviário"},
    "MOTV.SA": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Exploração de Rodovias"},
    "CRTE.SA": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Exploração de Rodovias"},
    "ECOR.SA": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Exploração de Rodovias"},
    "TPIS.SA": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Exploração de Rodovias"},
    "AGRU.SA": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Serviços de Apoio e Armazenagem"},
    "HMOB.SA": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Serviços de Apoio e Armazenagem"},
    "IVPR.SA": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Serviços de Apoio e Armazenagem"},
    "PSVM.SA": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Serviços de Apoio e Armazenagem"},
    "STBP.SA": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Serviços de Apoio e Armazenagem"},
    "PORT.SA": {"setor": "Bens Industriais", "subsetor": "Transporte", "segmento": "Serviços de Apoio e Armazenagem"},
    "CTAX.SA": {"setor": "Bens Industriais", "subsetor": "Serviços Diversos", "segmento": "Serviços Diversos"},
    "BBML.SA": {"setor": "Bens Industriais", "subsetor": "Serviços Diversos", "segmento": "Serviços Diversos"},
    "DTCY.SA": {"setor": "Bens Industriais", "subsetor": "Serviços Diversos", "segmento": "Serviços Diversos"},
    "ALPK.SA": {"setor": "Bens Industriais", "subsetor": "Serviços Diversos", "segmento": "Serviços Diversos"},
    "GGPS.SA": {"setor": "Bens Industriais", "subsetor": "Serviços Diversos", "segmento": "Serviços Diversos"},
    "PRNR.SA": {"setor": "Bens Industriais", "subsetor": "Serviços Diversos", "segmento": "Serviços Diversos"},
    "SEQL.SA": {"setor": "Bens Industriais", "subsetor": "Serviços Diversos", "segmento": "Serviços Diversos"},
    "VLID.SA": {"setor": "Bens Industriais", "subsetor": "Serviços Diversos", "segmento": "Serviços Diversos"},
    "EPAR.SA": {"setor": "Bens Industriais", "subsetor": "Comércio", "segmento": "Material de Transporte"},
    "MMAQ.SA": {"setor": "Bens Industriais", "subsetor": "Comércio", "segmento": "Material de Transporte"},
    "RBNS.SA": {"setor": "Bens Industriais", "subsetor": "Comércio", "segmento": "Material de Transporte"},
    "WLMM.SA": {"setor": "Bens Industriais", "subsetor": "Comércio", "segmento": "Material de Transporte"},
    "TTEN.SA": {"setor": "Consumo Não Cíclico", "subsetor": "Agropecuária", "segmento": "Agricultura"},
    "GRAO.SA": {"setor": "Consumo Não Cíclico", "subsetor": "Agropecuária", "segmento": "Agricultura"},
    "AGXY.SA": {"setor": "Consumo Não Cíclico", "subsetor": "Agropecuária", "segmento": "Agricultura"},
    "APTI.SA": {"setor": "Consumo Não Cíclico", "subsetor": "Agropecuária", "segmento": "Agricultura"},
    "SOJA.SA": {"setor": "Consumo Não Cíclico", "subsetor": "Agropecuária", "segmento": "Agricultura"},
    "AGRO.SA": {"setor": "Consumo Não Cíclico", "subsetor": "Agropecuária", "segmento": "Agricultura"},
    "CTCA.SA": {"setor": "Consumo Não Cíclico", "subsetor": "Agropecuária", "segmento": "Agricultura"},
    "EGGY.SA": {"setor": "Consumo Não Cíclico", "subsetor": "Agropecuária", "segmento": "Agricultura"},
    "SLCE.SA": {"setor": "Consumo Não Cíclico", "subsetor": "Agropecuária", "segmento": "Agricultura"},
    "LAND.SA": {"setor": "Consumo Não Cíclico", "subsetor": "Agropecuária", "segmento": "Agricultura"},
    "JALL.SA": {"setor": "Consumo Não Cíclico", "subsetor": "Alimentos Processados", "segmento": "Açúcar e Álcool"},
    "SMTO.SA": {"setor": "Consumo Não Cíclico", "subsetor": "Alimentos Processados", "segmento": "Açúcar e Álcool"},
    "BRFS.SA": {"setor": "Consumo Não Cíclico", "subsetor": "Alimentos Processados", "segmento": "Carnes e Derivados"},
    "BAUH.SA": {"setor": "Consumo Não Cíclico", "subsetor": "Alimentos Processados", "segmento": "Carnes e Derivados"},
    "JBSS.SA": {"setor": "Consumo Não Cíclico", "subsetor": "Alimentos Processados", "segmento": "Carnes e Derivados"},
    "MRFG.SA": {"setor": "Consumo Não Cíclico", "subsetor": "Alimentos Processados", "segmento": "Carnes e Derivados"},
    "BEEF.SA": {"setor": "Consumo Não Cíclico", "subsetor": "Alimentos Processados", "segmento": "Carnes e Derivados"},
    "MNPR.SA": {"setor": "Consumo Não Cíclico", "subsetor": "Alimentos Processados", "segmento": "Carnes e Derivados"},
    "CAML.SA": {"setor": "Consumo Não Cíclico", "subsetor": "Alimentos Processados", "segmento": "Alimentos Diversos"},
    "JOPA.SA": {"setor": "Consumo Não Cíclico", "subsetor": "Alimentos Processados", "segmento": "Alimentos Diversos"},
    "MDIA.SA": {"setor": "Consumo Não Cíclico", "subsetor": "Alimentos Processados", "segmento": "Alimentos Diversos"},
    "ODER.SA": {"setor": "Consumo Não Cíclico", "subsetor": "Alimentos Processados", "segmento": "Alimentos Diversos"},
    "ABEV.SA": {"setor": "Consumo Não Cíclico", "subsetor": "Bebidas", "segmento": "Cervejas e Refrigerantes"},
    "NATU.SA": {"setor": "Consumo Não Cíclico", "subsetor": "Produtos de Uso Pessoal e Limpeza", "segmento": "Produtos de Uso Pessoal"},
    "BOBR.SA": {"setor": "Consumo Não Cíclico", "subsetor": "Produtos de Uso Pessoal e Limpeza", "segmento": "Produtos de Limpeza"},
    "ASAI.SA": {"setor": "Consumo Não Cíclico", "subsetor": "Comércio e Distribuição", "segmento": "Alimentos"},
    "CAFR.SA": {"setor": "Consumo Não Cíclico", "subsetor": "Comércio e Distribuição", "segmento": "Alimentos"},
    "GMAT.SA": {"setor": "Consumo Não Cíclico", "subsetor": "Comércio e Distribuição", "segmento": "Alimentos"},
    "PCAR.SA": {"setor": "Consumo Não Cíclico", "subsetor": "Comércio e Distribuição", "segmento": "Alimentos"},
    "AVLL.SA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "CALI.SA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "CURY.SA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "CYRE.SA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "DIRR.SA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "EVEN.SA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "EZTC.SA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "FIEI.SA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "GFSA.SA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "HBOR.SA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "INNC.SA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "JHSF.SA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "JFEN.SA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "KLAS.SA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "LAVV.SA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "MELK.SA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "MTRE.SA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "MDNE.SA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "MRVE.SA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "PDGR.SA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "PLPL.SA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Incorporações"},
    "CCTY.SA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Intermediação Imobiliária"},
    "RDNI.SA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Intermediação Imobiliária"},
    "RSID.SA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Intermediação Imobiliária"},
    "TCSA.SA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Intermediação Imobiliária"},
    "TEGA.SA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Intermediação Imobiliária"},
    "TEND.SA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Intermediação Imobiliária"},
    "TRIS.SA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Intermediação Imobiliária"},
    "VIVR.SA": {"setor": "Consumo Cíclico", "subsetor": "Construção Civil", "segmento": "Intermediação Imobiliária"},
    "CEDO.SA": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Fios e Tecidos"},
    "CTNM.SA": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Fios e Tecidos"},
    "DOHL.SA": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Fios e Tecidos"},
    "CATA.SA": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Vestuário"},
    "CTKA.SA": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Vestuário"},
    "PTNT.SA": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Vestuário"},
    "CTSA.SA": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Vestuário"},
    "SGPS.SA": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Vestuário"},
    "TXRX.SA": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Vestuário"},
    "TFCO.SA": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Vestuário"},
    "ALPA.SA": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Calçados"},
    "CAMB.SA": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Calçados"},
    "GRND.SA": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Calçados"},
    "VULC.SA": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Calçados"},
    "MNDL.SA": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Acessórios"},
    "TECN.SA": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Acessórios"},
    "VIVA.SA": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Acessórios"},
    "WHRL.SA": {"setor": "Consumo Cíclico", "subsetor": "Tecidos, Vestuário e Calçados", "segmento": "Acessórios"},
    "TOKY.SA": {"setor": "Consumo Cíclico", "subsetor": "Automóveis e Motocicletas", "segmento": "Automóveis e Motocicletas"},
    "UCAS.SA": {"setor": "Consumo Cíclico", "subsetor": "Automóveis e Motocicletas", "segmento": "Automóveis e Motocicletas"},
    "WEST.SA": {"setor": "Consumo Cíclico", "subsetor": "Automóveis e Motocicletas", "segmento": "Automóveis e Motocicletas"},
    "HETA.SA": {"setor": "Consumo Cíclico", "subsetor": "Automóveis e Motocicletas", "segmento": "Peças e Acessórios"},
    "AMOB.SA": {"setor": "Consumo Cíclico", "subsetor": "Automóveis e Motocicletas", "segmento": "Peças e Acessórios"},
    "MYPK.SA": {"setor": "Consumo Cíclico", "subsetor": "Automóveis e Motocicletas", "segmento": "Peças e Acessórios"},
    "LEVE.SA": {"setor": "Consumo Cíclico", "subsetor": "Automóveis e Motocicletas", "segmento": "Peças e Acessórios"},
    "PLAS.SA": {"setor": "Consumo Cíclico", "subsetor": "Automóveis e Motocicletas", "segmento": "Peças e Acessórios"},
    "HOOT.SA": {"setor": "Consumo Cíclico", "subsetor": "Hoteis e Restaurantes", "segmento": "Restaurantes"},
    "MEAL.SA": {"setor": "Consumo Cíclico", "subsetor": "Hoteis e Restaurantes", "segmento": "Restaurantes"},
    "ZAMP.SA": {"setor": "Consumo Cíclico", "subsetor": "Hoteis e Restaurantes", "segmento": "Restaurantes"},
    "BMKS.SA": {"setor": "Consumo Cíclico", "subsetor": "Hoteis e Restaurantes", "segmento": "Hotéis"},
    "ESTR.SA": {"setor": "Consumo Cíclico", "subsetor": "Hoteis e Restaurantes", "segmento": "Hotéis"},
    "RVEE.SA": {"setor": "Consumo Cíclico", "subsetor": "Hoteis e Restaurantes", "segmento": "Hotéis"},
    "AHEB.SA": {"setor": "Consumo Cíclico", "subsetor": "Diversos", "segmento": "Atividades Esportivas"},
    "SHOW.SA": {"setor": "Consumo Cíclico", "subsetor": "Diversos", "segmento": "Atividades Esportivas"},
    "CVCB.SA": {"setor": "Consumo Cíclico", "subsetor": "Diversos", "segmento": "Viagens e Turismo"},
    "SMFT.SA": {"setor": "Consumo Cíclico", "subsetor": "Diversos", "segmento": "Viagens e Turismo"},
    "ANIM.SA": {"setor": "Consumo Cíclico", "subsetor": "Diversos", "segmento": "Programas de Fidelização"},
    "ATED.SA": {"setor": "Consumo Cíclico", "subsetor": "Diversos", "segmento": "Educação"},
    "BIED.SA": {"setor": "Consumo Cíclico", "subsetor": "Diversos", "segmento": "Educação"},
    "COGN.SA": {"setor": "Consumo Cíclico", "subsetor": "Diversos", "segmento": "Educação"},
    "CSED.SA": {"setor": "Consumo Cíclico", "subsetor": "Diversos", "segmento": "Educação"},
    "SEER.SA": {"setor": "Consumo Cíclico", "subsetor": "Diversos", "segmento": "Educação"},
    "VTRU.SA": {"setor": "Consumo Cíclico", "subsetor": "Diversos", "segmento": "Educação"},
    "YDUQ.SA": {"setor": "Consumo Cíclico", "subsetor": "Diversos", "segmento": "Educação"},
    "RENT.SA": {"setor": "Consumo Cíclico", "subsetor": "Aluguel de carros", "segmento": "Aluguel de Carros"},
    "MOVI.SA": {"setor": "Consumo Cíclico", "subsetor": "Aluguel de carros", "segmento": "Aluguel de Carros"},
    "VAMO.SA": {"setor": "Consumo Cíclico", "subsetor": "Aluguel de carros", "segmento": "Aluguel de Carros"},
    "DOTZ.SA": {"setor": "Consumo Cíclico", "subsetor": "Programas de Fidelidade", "segmento": "Programas de Fidelidade"},
    "AZZA.SA": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Tecidos, Vestuário e Calçados"},
    "CEAB.SA": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Tecidos, Vestuário e Calçados"},
    "CGRA.SA": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Tecidos, Vestuário e Calçados"},
    "GUAR.SA": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Tecidos, Vestuário e Calçados"},
    "AMAR.SA": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Tecidos, Vestuário e Calçados"},
    "LREN.SA": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Tecidos, Vestuário e Calçados"},
    "VSTE.SA": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Tecidos, Vestuário e Calçados"},
    "ALLD.SA": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Eletrodomésticos"},
    "BHIA.SA": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Eletrodomésticos"},
    "MGLU.SA": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Eletrodomésticos"},
    "AMER.SA": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Eletrodomésticos"},
    "ESPA.SA": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Eletrodomésticos"},
    "SBFG.SA": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Eletrodomésticos"},
    "LLBI.SA": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Móveis"},
    "PETZ.SA": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Produtos Diversos"},
    "LJQQ.SA": {"setor": "Consumo Cíclico", "subsetor": "Comércio", "segmento": "Produtos Diversos"},
    "BIOM.SA": {"setor": "Saúde", "subsetor": "Medicamentos e Outros Produtos", "segmento": "Medicamentos e Outros Produtos"},
    "NRTQ.SA": {"setor": "Saúde", "subsetor": "Medicamentos e Outros Produtos", "segmento": "Medicamentos e Outros Produtos"},
    "OFSA.SA": {"setor": "Saúde", "subsetor": "Medicamentos e Outros Produtos", "segmento": "Medicamentos e Outros Produtos"},
    "AALR.SA": {"setor": "Saúde", "subsetor": "Serviços Médico - Hospitalares, Análises e Diagnósticos", "segmento": "Análises e Diagnósticos"},
    "DASA.SA": {"setor": "Saúde", "subsetor": "Serviços Médico - Hospitalares, Análises e Diagnósticos", "segmento": "Análises e Diagnósticos"},
    "FLRY.SA": {"setor": "Saúde", "subsetor": "Serviços Médico - Hospitalares, Análises e Diagnósticos", "segmento": "Análises e Diagnósticos"},
    "HAPV.SA": {"setor": "Saúde", "subsetor": "Serviços Médico - Hospitalares, Análises e Diagnósticos", "segmento": "Análises e Diagnósticos"},
    "MATD.SA": {"setor": "Saúde", "subsetor": "Serviços Médico - Hospitalares, Análises e Diagnósticos", "segmento": "Análises e Diagnósticos"},
    "ODPV.SA": {"setor": "Saúde", "subsetor": "Serviços Médico - Hospitalares, Análises e Diagnósticos", "segmento": "Análises e Diagnósticos"},
    "ONCO.SA": {"setor": "Saúde", "subsetor": "Serviços Médico - Hospitalares, Análises e Diagnósticos", "segmento": "Análises e Diagnósticos"},
    "QUAL.SA": {"setor": "Saúde", "subsetor": "Serviços Médico - Hospitalares, Análises e Diagnósticos", "segmento": "Serviços Médico - Hospitalares"},
    "RDOR.SA": {"setor": "Saúde", "subsetor": "Serviços Médico - Hospitalares, Análises e Diagnósticos", "segmento": "Serviços Médico - Hospitalares"},
    "BALM.SA": {"setor": "Saúde", "subsetor": "Comércio e Distribuição", "segmento": "Medicamentos"},
    "LMED.SA": {"setor": "Saúde", "subsetor": "Comércio e Distribuição", "segmento": "Medicamentos"},
    "BLAU.SA": {"setor": "Saúde", "subsetor": "Medicamentos e Outros Produtos", "segmento": "Medicamentos e Outros Produtos"},
    "DMVF.SA": {"setor": "Saúde", "subsetor": "Medicamentos e Outros Produtos", "segmento": "Medicamentos e Outros Produtos"},
    "PNVL.SA": {"setor": "Saúde", "subsetor": "Medicamentos e Outros Produtos", "segmento": "Medicamentos e Outros Produtos"},
    "EUFA.SA": {"setor": "Saúde", "subsetor": "Medicamentos e Outros Produtos", "segmento": "Medicamentos e Outros Produtos"},
    "HYPE.SA": {"setor": "Saúde", "subsetor": "Medicamentos e Outros Produtos", "segmento": "Medicamentos e Outros Produtos"},
    "PGMN.SA": {"setor": "Saúde", "subsetor": "Medicamentos e Outros Produtos", "segmento": "Medicamentos e Outros Produtos"},
    "PFRM.SA": {"setor": "Saúde", "subsetor": "Medicamentos e Outros Produtos", "segmento": "Medicamentos e Outros Produtos"},
    "RADL.SA": {"setor": "Saúde", "subsetor": "Medicamentos e Outros Produtos", "segmento": "Medicamentos e Outros Produtos"},
    "VVEO.SA": {"setor": "Saúde", "subsetor": "Medicamentos e Outros Produtos", "segmento": "Medicamentos e Outros Produtos"},
    "INTB.SA": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "MLAS.SA": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "POSI.SA": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "BMOB.SA": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "BRQB.SA": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "ENJU.SA": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "EXPB.SA": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "REAG.SA": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "IFCM.SA": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "LWSA.SA": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "CASH.SA": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "NGRD.SA": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "PDTC.SA": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "QUSW.SA": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "TRAD.SA": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "TOTS.SA": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "LVTC.SA": {"setor": "Tecnologia da Informação", "subsetor": "Programas e Serviços", "segmento": "Programas e Serviços"},
    "BRST.SA": {"setor": "Comunicações", "subsetor": "Telecomunicações", "segmento": "Telecomunicações"},
    "DESK.SA": {"setor": "Comunicações", "subsetor": "Telecomunicações", "segmento": "Telecomunicações"},
    "OIBR.SA": {"setor": "Comunicações", "subsetor": "Telecomunicações", "segmento": "Telecomunicações"},
    "TELB.SA": {"setor": "Comunicações", "subsetor": "Telecomunicações", "segmento": "Telecomunicações"},
    "VIVT.SA": {"setor": "Comunicações", "subsetor": "Telecomunicações", "segmento": "Telecomunicações"},
    "TIMS.SA": {"setor": "Comunicações", "subsetor": "Telecomunicações", "segmento": "Telecomunicações"},
    "FIQE.SA": {"setor": "Comunicações", "subsetor": "Telecomunicações", "segmento": "Telecomunicações"},
    "AESO.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "AFLT.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "ALUP.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "CBEE.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "AURE.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "CEBR.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "CEED.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "CLSC.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "GPAR.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "CMIG.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "CEEB.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "COCE.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "COMR.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "CPLE.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "CPFE.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "EKTR.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "ELET.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "EMAE.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "ENGI.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "ENMT.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "ENEV.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "EGIE.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "EQPA.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "EQMA.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "EQTL.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "GEPA.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "ISAE.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "LIGH.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "LIGT.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "NEOE.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "SRNA.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "PRMN.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "REDE.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "RNEW.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "TAEE.SA": {"setor": "Utilidade Pública", "subsetor": "Energia Elétrica", "segmento": "Energia Elétrica"},
    "AMBP.SA": {"setor": "Utilidade Pública", "subsetor": "Água e Saneamento", "segmento": "Água e Saneamento"},
    "CASN.SA": {"setor": "Utilidade Pública", "subsetor": "Água e Saneamento", "segmento": "Água e Saneamento"},
    "CSMG.SA": {"setor": "Utilidade Pública", "subsetor": "Água e Saneamento", "segmento": "Água e Saneamento"},
    "IGSN.SA": {"setor": "Utilidade Pública", "subsetor": "Água e Saneamento", "segmento": "Água e Saneamento"},
    "ORVR.SA": {"setor": "Utilidade Pública", "subsetor": "Água e Saneamento", "segmento": "Água e Saneamento"},
    "SBSP.SA": {"setor": "Utilidade Pública", "subsetor": "Água e Saneamento", "segmento": "Água e Saneamento"},
    "SAPR.SA": {"setor": "Utilidade Pública", "subsetor": "Água e Saneamento", "segmento": "Água e Saneamento"},
    "CEGR.SA": {"setor": "Utilidade Pública", "subsetor": "Gás", "segmento": "Gás"},
    "CGAS.SA": {"setor": "Utilidade Pública", "subsetor": "Gás", "segmento": "Gás"},
    "PASS.SA": {"setor": "Utilidade Pública", "subsetor": "Gás", "segmento": "Gás"},
    "ABCB.SA": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "RPAD.SA": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "BAZA.SA": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "BMGB.SA": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "BPAN.SA": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "BGIP.SA": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "BEES.SA": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "BPAR.SA": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "BRSR.SA": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "BRBI.SA": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "BBDC.SA": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "BBAS.SA": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "BSLI.SA": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "BPAC.SA": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "INBR.SA": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "ITUB.SA": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "BMEB.SA": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "BMIN.SA": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "BNBR.SA": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "PINE.SA": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "SANB.SA": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Bancos"},
    "MERC.SA": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Financeiras Diversas"},
    "BSCS.SA": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Financeiras Diversas"},
    "RBRA.SA": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Financeiras Diversas"},
    "PLSC.SA": {"setor": "Financeiro", "subsetor": "Intermediários Financeiros", "segmento": "Financeiras Diversas"},
    "G2DI.SA": {"setor": "Financeiro", "subsetor": "Gestão de Recursos e Investimentos", "segmento": "Gestão de Recursos e Investimentos"},
    "GPIV.SA": {"setor": "Financeiro", "subsetor": "Gestão de Recursos e Investimentos", "segmento": "Gestão de Recursos e Investimentos"},
    "PPLA.SA": {"setor": "Financeiro", "subsetor": "Gestão de Recursos e Investimentos", "segmento": "Gestão de Recursos e Investimentos"},
    "B3SA.SA": {"setor": "Financeiro", "subsetor": "Serviços Financeiros Diversos", "segmento": "Bolsa de Valores"},
    "CSUD.SA": {"setor": "Financeiro", "subsetor": "Serviços Financeiros Diversos", "segmento": "Cartões de Crédito"},
    "EFXB.SA": {"setor": "Financeiro", "subsetor": "Serviços Financeiros Diversos", "segmento": "Cartões de Crédito"},
    "EVTC.SA": {"setor": "Financeiro", "subsetor": "Serviços Financeiros Diversos", "segmento": "Cartões de Crédito"},
    "XPBR.SA": {"setor": "Financeiro", "subsetor": "Serviços Financeiros Diversos", "segmento": "Corretoras de Valores e Commodities"},
    "BBSE.SA": {"setor": "Financeiro", "subsetor": "Previdência e Seguros", "segmento": "Seguradoras"},
    "CXSE.SA": {"setor": "Financeiro", "subsetor": "Previdência e Seguros", "segmento": "Seguradoras"},
    "PSSA.SA": {"setor": "Financeiro", "subsetor": "Previdência e Seguros", "segmento": "Seguradoras"},
    "IRBR.SA": {"setor": "Financeiro", "subsetor": "Previdência e Seguros", "segmento": "Resseguradoras"},
    "WIZC.SA": {"setor": "Financeiro", "subsetor": "Previdência e Seguros", "segmento": "Corretores de Seguros"},
    "ALOS.SA": {"setor": "Financeiro", "subsetor": "Exploração de Imóveis", "segmento": "Exploração de Imóveis"},
    "GSHP.SA": {"setor": "Financeiro", "subsetor": "Exploração de Imóveis", "segmento": "Shopping Centers"},
    "HBTS.SA": {"setor": "Financeiro", "subsetor": "Exploração de Imóveis", "segmento": "Exploração de Imóveis"},
    "HBRE.SA": {"setor": "Financeiro", "subsetor": "Exploração de Imóveis", "segmento": "Exploração de Imóveis"},
    "IGBR.SA": {"setor": "Financeiro", "subsetor": "Exploração de Imóveis", "segmento": "Exploração de Imóveis"},
    "IGTI.SA": {"setor": "Financeiro", "subsetor": "Exploração de Imóveis", "segmento": "Exploração de Imóveis"},
    "LOGG.SA": {"setor": "Financeiro", "subsetor": "Exploração de Imóveis", "segmento": "Exploração de Imóveis"},
    "MNZC.SA": {"setor": "Financeiro", "subsetor": "Exploração de Imóveis", "segmento": "Exploração de Imóveis"},    
    "MULT.SA": {"setor": "Financeiro", "subsetor": "Exploração de Imóveis", "segmento": "Exploração de Imóveis"},
    "PEAB.SA": {"setor": "Financeiro", "subsetor": "Exploração de Imóveis", "segmento": "Exploração de Imóveis"},
    "SCAR.SA": {"setor": "Financeiro", "subsetor": "Exploração de Imóveis", "segmento": "Exploração de Imóveis"},
    "SYNE.SA": {"setor": "Financeiro", "subsetor": "Exploração de Imóveis", "segmento": "Exploração de Imóveis"},
    "LPSB.SA": {"setor": "Financeiro", "subsetor": "Exploração de Imóveis", "segmento": "Intermediação Imobiliária"},
    "NEXP.SA": {"setor": "Financeiro", "subsetor": "Exploração de Imóveis", "segmento": "Intermediação Imobiliária"},
    "ADMF.SA": {"setor": "Financeiro", "subsetor": "Holdings Diversificadas", "segmento": "Holdings Diversificadas"},
    "ITSA.SA": {"setor": "Financeiro", "subsetor": "Holdings Diversificadas", "segmento": "Holdings Diversificadas"},
    "MOAR.SA": {"setor": "Financeiro", "subsetor": "Holdings Diversificadas", "segmento": "Holdings Diversificadas"},
    "SIMH.SA": {"setor": "Financeiro", "subsetor": "Holdings Diversificadas", "segmento": "Holdings Diversificadas"},
    "CTBA.SA": {"setor": "Financeiro", "subsetor": "Outros Títulos", "segmento": "Outros Títulos"},
    "MCRJ.SA": {"setor": "Financeiro", "subsetor": "Outros Títulos", "segmento": "Outros Títulos"},
    "PMSP.SA": {"setor": "Financeiro", "subsetor": "Outros Títulos", "segmento": "Outros Títulos"},
    "QVQP.SA": {"setor": "Outros", "subsetor": "Outros", "segmento": "Outros"},
    "BETP.SA": {"setor": "Outros", "subsetor": "Outros", "segmento": "Outros"},
    "MAPT.SA": {"setor": "Outros", "subsetor": "Outros", "segmento": "Outros"},
    "FICT.SA": {"setor": "Outros", "subsetor": "Outros", "segmento": "Outros"},
    "OPGM.SA": {"setor": "Outros", "subsetor": "Outros", "segmento": "Outros"},
    "FIGE.SA": {"setor": "Outros", "subsetor": "Outros", "segmento": "Outros"},
    "PPAR.SA": {"setor": "Outros", "subsetor": "Outros", "segmento": "Outros"},
    "PRPT.SA": {"setor": "Outros", "subsetor": "Outros", "segmento": "Outros"},
    "OPSE.SA": {"setor": "Outros", "subsetor": "Outros", "segmento": "Outros"},
    "OPTS.SA": {"setor": "Outros", "subsetor": "Outros", "segmento": "Outros"},
}